README.md, client/README.md
Add badges for godocs and the latest release.
=> chore: Add godoc and release badges

.github/workflows/release.yaml, .github/workflows/snaphot.yaml, .goreleaser-ci.yml, docs/modules/api/pages/index.adoc
- Update actions to publish the protobufs to BSR
- Add documentation about using the BSR
- Fix deprecated setting on GoReleaser config
=> chore(ci): Publish protos to Buf schema registry

deploy/charts/cerbos/Chart.yaml, docs/antora-playbook.yml, docs/antora.yml, docs/build.sh, hack/scripts/prep-release.sh
This change paves the way to having previous versions of the
documentation available to view through the docs site.
It will also help with permalinking because the URLs are versioned by
the application version.
=> chore: Configure docs to support multiple versions

docs/modules/tutorials/pages/photo-share/index.adoc
There are a few lines missing from the tests, this is a minor tweak.
=> docs: Update index.adoc to fix the results of the test

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/feature.yaml
Signed-off-by: serdar <serdar@cerbos.dev>
Adds issue templates for bugs and feature requests.
Fixes: #218
=> chore: add issue templates

internal/storage/git/store_test.go
Signed-off-by: serdar <serdar@cerbos.dev>
A small bug in the tests caught me several times :)
=> bug: fix a flaky test in TestUpdateStore

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.5.0.adoc
=> docs: Add v0.5.0 release notes

docs/modules/api/pages/index.adoc
=> docs: Add link to Java SDK

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.6.0.adoc
=> docs: Add v0.6.0 release notes

.goreleaser-ci.yml, docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.7.0.adoc
=> chore(release): Add 0.7.0 release notes

docs/modules/api/pages/index.adoc
=> docs: Document how to obtain gRPC stubs

docs/modules/policies/pages/conditions.adoc, docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.8.0.adoc
=> chore(release): Add 0.8.0 release notes

internal/codegen/cel.go, internal/codegen/codegen.go, internal/codegen/rego.go, internal/compile/conditions.go, internal/conditions/cel.go, internal/conditions/cerbos_lib.go, internal/conditions/cerbos_lib_test.go, internal/conditions/types/hierarchy.go, internal/conditions/types/type_adapter.go
This is a residual task from #327 to re-organise the code
=> chore(refactor): Move CEL code to conditions package

internal/compile/conditions.go
Evaluates global variables more efficiently by re-using compiled expressions.
=> enhancement: Re-use compiled global expressions

docs/modules/api/pages/index.adoc
Updates documentation on how to obtain protobuf definitions.
Fixes #337  
=> docs: Document how to obtain protobuf definitions

internal/server/middleware.go, internal/server/server.go
Produces helpful error messages if users try to access the Admin API
or the Playground API when they are disabled by configuration.
=> enhancement: Better errors when disabled services are accessed

.goreleaser-ci.yml, .goreleaser-dev.yml, Makefile, deploy/linux/conf/cerbos.yaml, deploy/linux/scripts/post-install.sh, deploy/linux/scripts/pre-remove.sh, deploy/linux/unit/cerbos.service, docs/modules/ROOT/pages/installation/binary.adoc, docs/modules/ROOT/partials/attributes.adoc, docs/modules/deployment/nav.adoc, docs/modules/deployment/pages/systemd.adoc
Adds experimental support for building packages for distributions that
use DEB and RPM package formats.
=> feat: Linux packages

.github/workflows/release.yaml, .goreleaser-ci.yml, docs/modules/ROOT/pages/installation/binary.adoc, tools/go.mod, tools/go.sum
=> feat: Homebrew formula

.github/workflows/test-matrix.yaml, .goreleaser.yml
=> chore(ci): Disable test matrix and Windows build

docs/antora-playbook.yml, hack/scripts/prep-release.sh
Generating from branches allows us to update documentation for previous releases if we find any bugs in them
=> docs: Generate docs from branches

docs/modules/deployment/nav.adoc, docs/modules/deployment/pages/serverless-faas.adoc
Adds a section to the documentation on how to deploy Cerbos to AWS Lambda.
Fixes #432
=> docs: Add AWS Lambda deployment option

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.10.0.adoc
=> chore(release): Add 0.10.0 release notes

.github/workflows/release.yaml, .github/workflows/snaphot.yaml, .goreleaser.yml
- Configure the build to produce a container image tagged with `latest`
- Create a manifest list for the `dev` image
- Remove JFrog
=> chore(ci): Add latest tag and remove JFrog

docs/modules/tutorials/pages/orm/prisma/index.adoc
=> docs: References variable for container image

docs/modules/tutorials/assets/images/jwt-token.png, docs/modules/tutorials/nav.adoc, docs/modules/tutorials/pages/authentication/auth0/index.adoc, docs/modules/tutorials/pages/authentication/jwt/index.adoc, docs/modules/tutorials/pages/authentication/magic/index.adoc, docs/modules/tutorials/pages/orm/prisma/index.adoc
=> docs(backport): Add tutorials 

.github/actions/antora-docs/action.yaml, .github/workflows/docs.yaml, .github/workflows/release.yaml, .github/workflows/snaphot.yaml, hack/scripts/prep-release.sh
- Publish docs on push to any release branch
- Update Antora
- Keep author mode on in release branches to avoid build  failures 
=> chore(ci): Add docs publication workflow

internal/storage/git/store.go, internal/storage/git/store_test.go
Update the Git store to handle schema add/update/delete events.
=> enhancement: Add schema event handling to git store

internal/storage/blob/store_test.go
=> chore(test): Add test for schema events to blob store

docs/modules/api/pages/admin_api.adoc
Adds documentation for Admin API endpoints of schema feature.
=> docs: Add docs for schema Admin API services

docs/modules/api/pages/admin_api.adoc, docs/modules/policies/pages/schemas.adoc
=> docs: Make the Admin API docs follow a consistent style

internal/storage/index/builder.go
=> enhancement: Log the number of policies found on startup

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.11.0.adoc
=> chore(release): Add 0.11.0 release notes

internal/engine/planner.go, internal/test/testdata/query_planner/suite/maggie.yaml
Simplify query plan's unary logical operation expressions
=> enhancement: Simplify query plan logical operation expressions

.github/codecov.yaml, .github/workflows/pr-test.yaml, .github/workflows/snaphot.yaml, .gitignore, Makefile
Upload test coverage data to CodeCov.
=> chore(ci): Add CodeCov integration

docs/modules/ROOT/pages/index.adoc
Add some points around why Cerbos is designed a a standalone service.
=> docs: add service docs

.github/actions/antora-docs/action.yaml, .goreleaser.yml, Makefile, docs/build.sh
- Create a separate archive for cerbosctl
- Fix deprecated empty_dir setting in Linux package
- Update Antora to 3.0.1
=> chore: Update Antora and Goreleaser config

docs/modules/ROOT/pages/quickstart.adoc, docs/modules/tutorials/nav.adoc, docs/supplemental-ui/partials/header-content.hbs
=> docs: Add links to guide

docs/modules/api/pages/index.adoc, docs/modules/policies/images/decision_flow.png, docs/modules/policies/images/hierarchy.png, docs/modules/policies/nav.adoc, docs/modules/policies/pages/index.adoc, docs/modules/policies/pages/principal_policies.adoc, docs/modules/policies/pages/resource_policies.adoc, docs/modules/policies/pages/scoped_policies.adoc
Document how scoped policies work.
=> docs: Add scoped policies documentation

hack/loadtest/.gitignore, hack/loadtest/README.md, hack/loadtest/docker-compose.yml, hack/loadtest/k6/check.js, hack/loadtest/loadtest.sh
- Refactor launch script to run just one test at a time
- Add test scenarios to K6 script and make them configurable via env vars
- Create a separate work directory to store temporary test-related artefacts
=> chore(test): Tweak load test script

hack/loadtest/check.js
After each request made during the load tests, the response will be compared with the wanted response.
=> chore(test): Add response and wantedResponse check for the load tests

hack/loadtest/conf/cerbos/disk.yml, hack/loadtest/conf/grafana/dashboards/cerbos.json, internal/compile/manager.go, internal/observability/metrics/metrics.go, internal/schema/schema.go
Report metrics about the caches (size, hits, misses).
Fixes #703
=> enhancement: Add cache metrics

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.14.0.adoc, docs/modules/releases/pages/v0.14.0/upgrade.adoc
=> chore(release): Add 0.14.0 release notes

e2e/blob/helmfile.yaml, e2e/git/helmfile.yaml, e2e/mysql/helmfile.yaml, e2e/postgres/helmfile.yaml, e2e/sqlite/helmfile.yaml, e2e/sqlserver/helmfile.yaml
=> chore(ci): Disable telemetry in E2E tests

internal/server/server.go
Replaces the HTTP health check with the new healthz option introduced in
the latest version of grpc-gateway. It includes the ability to check
individual services by passing the `service` query parameter.
=> enhancement: Improve HTTP health check

docs/modules/ROOT/partials/attributes.adoc, docs/modules/policies/nav.adoc, docs/modules/policies/pages/authoring_tips.adoc, docs/modules/policies/pages/index.adoc
=> docs: Add editor configuration docs

docs/modules/policies/images/jetbrains-menu.png, docs/modules/policies/pages/authoring_tips.adoc
This PR adds JetBrains and VSCode authoring tips to the documentation.
=> docs: Add JetBrains and VSCode authoring tips

.gitattributes, docs/modules/cli/pages/cerbos.adoc, docs/modules/releases/assets/images/repl.gif, docs/modules/releases/assets/images/schema_edit.gif, docs/modules/releases/assets/images/test_output.png, docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.15.0.adoc
=> chore(release): Add 0.15.0 release notes

docs/modules/policies/pages/compile.adoc
=> docs: Fix ID attribute in testing docs

deploy/charts/cerbos/Chart.yaml, docs/antora-playbook.yml, docs/antora.yml, docs/modules/policies/pages/compile.adoc, internal/storage/git/store.go
Backport #822 and #823 to the 0.15 branch
=> fix(backport): Fixes to include in v0.15.1 (#822 and #823)

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.15.1.adoc
=> chore(release): Add 0.15.1 release notes

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.15.1.adoc
=> chore(backport): Add 0.15.1 release notes (#825)

internal/engine/engine.go
Currently, when no policy matches, no engine trace is generated. This is problematic when a test fails because `--verbose` gives no additional information.
This PR adds a trace event when the default effect is applied due to no matching policies. I also removed the short-circuit for when there are no checks present in the evaluation context, because this condition is also checked within `(*evaluationCtx).evaluate`.
Now, the verbose output is more helpful for diagnosing the test failure:
```
purchase_order - regional_operations.regional_emea_widgets_purchase_order.sendInvoice
action=sendInvoice
activated
effect → deny
No matching policies
```
=> enhancement: Add trace for denial due to no matching policies

docs/modules/configuration/pages/tracing.adoc, docs/modules/configuration/partials/fullconfiguration.adoc, internal/observability/tracing/conf.go
=> docs: Document Jaeger trace format

hack/dev/requests/plan_resources/req3.json, internal/engine/evaluator_test.go, internal/engine/planner.go, internal/engine/testdata/ast_build_expr.yaml, internal/test/testdata/query_planner/policies/principal_policy_macros.yaml, internal/test/testdata/query_planner/suite/macro_user.yaml
Adds new tests for the Query Planner.
=> test: Add the query planner tests

docs/modules/cli/pages/cerbos.adoc, docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.16.0.adoc
=> chore(release): Add 0.16.0 release notes

docs/modules/api/pages/index.adoc
=> docs: Add links to new SDKs

docs/antora.yml, docs/modules/glossary/nav.adoc, docs/modules/glossary/pages/index.adoc
=> docs: Add glossary

docs/antora.yml, docs/modules/glossary/nav.adoc, docs/modules/glossary/pages/index.adoc
=> docs(backport): Add glossary

docs/modules/ROOT/pages/quickstart.adoc, docs/modules/tutorials/nav.adoc
Make the demos easier to find.
=> docs: Add links to demos

README.md, docs/modules/api/pages/index.adoc
=> docs: Add new SDK links to README and docs

internal/engine/engine.go, internal/engine/planner.go, internal/test/testdata/query_planner/suite/donald_duck.yaml, internal/test/testdata/query_planner/suite/harry.yaml, internal/test/testdata/server/plan_resources/plan_case_03.yaml, internal/test/testdata/server/plan_resources/plan_case_04.yaml, internal/test/testdata/server/playground/proxy/pgp_rqp_case_04.yaml, internal/test/testdata/server/playground/proxy/pgp_rqp_case_05.yaml
=> fix: Return DENY from query plan when no policy or action matches

docs/modules/ROOT/pages/quickstart.adoc, docs/modules/tutorials/nav.adoc
Backport of #914 
Make the demos easier to find.
=> docs(backport): Add links to demos (#914)

README.md, docs/modules/api/pages/index.adoc
=> docs(backport): Add new SDK links to README and docs (#919)

e2e/blob/helmfile.yaml, e2e/git/helmfile.yaml, e2e/jaeger/helmfile.yaml, e2e/mysql/helmfile.yaml, e2e/postgres/helmfile.yaml, e2e/sqlite/helmfile.yaml, e2e/sqlserver/helmfile.yaml
The tests expect a much smaller limit to be in place than the defaults
=> chore(test): Update E2E test config for request limit tests

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.17.0.adoc
=> chore(release): Add 0.17.0 release notes

cmd/cerbosctl/version/version.go
=> fix: Cerbosctl version should fail gracefully

internal/engine/ast.go, internal/engine/planner_test.go, internal/test/testdata/query_planner/suite/donald_duck.yaml
Convert `NOT false` to `true` and so on.
=> enhancement: Optimise NOT conditions in query planner output

README.md
Showcase some users of Cerbos!
=> docs: Showcase users

README.md
=> docs: Add JavaScript SDK link to README

README.md, docs/modules/api/assets/images/dot-net.svg, docs/modules/api/pages/index.adoc
=> docs: Add links to .NET SDK

docs/modules/policies/pages/resource_policies.adoc
This is explicit in the code but I couldn't see it in the docs.
=> docs: Specify what happens when multiple rules match

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.18.0.adoc
=> chore(release): Add 0.18.0 release notes

docs/modules/policies/pages/derived_roles.adoc
=> docs: Use analogy to explain derived roles

internal/storage/git/store_test.go
=> chore(test): Fix flaky update store test

docs/modules/configuration/pages/tracing.adoc, docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.19.0.adoc
=> chore(release): Add 0.19.0 release notes

private/verify/verify.go, private/verify/verify_test.go
Adds a utility function to run policy tests and return `*policyv1.TestResults`
=> chore: Add function to run policy tests

hack/loadtest/docker-compose.yml, hack/loadtest/templates/requests/cr_req01.json.tpl, hack/loadtest/templates/requests/cr_req02.json.tpl
=> chore(perf): Add template for CheckResources request

.github/workflows/pr-test.yaml
Show preview URLs on docs PRs.
Not using the Netlify app as it's too invasive and there's no way to enable just previews.
=> chore(ci): Add docs preview

.github/workflows/pr-test.yaml
=> chore(ci): Deploy docs previews

internal/observability/tracing/tracing.go
=> chore(deps): Use latest otel semconv version

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.19.1.adoc
=> chore(release): Add 0.19.1 release notes

docs/modules/ROOT/pages/tutorial/02_resource-definition.adoc, docs/modules/ROOT/pages/tutorial/03_calling-cerbos.adoc, docs/modules/ROOT/pages/tutorial/04_testing-policies.adoc, docs/modules/ROOT/pages/tutorial/05_adding-conditions.adoc, docs/modules/ROOT/pages/tutorial/06_derived-roles.adoc, docs/modules/ROOT/pages/tutorial/07_principal-policies.adoc, docs/modules/ROOT/pages/tutorial/08_attribute-schema.adoc, docs/modules/ROOT/partials/attributes.adoc
=> docs: Fix broken links to tutorial files

docs/modules/ROOT/pages/tutorial/02_resource-definition.adoc, docs/modules/ROOT/pages/tutorial/03_calling-cerbos.adoc, docs/modules/ROOT/pages/tutorial/04_testing-policies.adoc, docs/modules/ROOT/pages/tutorial/05_adding-conditions.adoc, docs/modules/ROOT/pages/tutorial/06_derived-roles.adoc, docs/modules/ROOT/pages/tutorial/07_principal-policies.adoc, docs/modules/ROOT/pages/tutorial/08_attribute-schema.adoc, docs/modules/ROOT/partials/attributes.adoc
=> docs(backport): Fix broken links to tutorial files (#1157)

.github/workflows/pr-title.yaml
=> chore(ci): Make PR labels job optional

internal/server/conf.go, internal/server/conf_test.go, internal/server/server.go
I noticed that the server warns about a security risk on the admin API if you continue to use `cerbos` as the username, even if you change the password. I don't think that should produce a warning on the basis that security comes from a strong password with a hard-to-crack hash, not the username being hard to guess.
Currently, if you change the password to an different hash of the same plaintext (e.g. by copy-pasting from the [docs](https://docs.cerbos.dev/cerbos/latest/configuration/server.html#_generating_a_password_hash)), it doesn't recognise that you're still using the default password, so you can avoid the warning without actually improving the security.
This PR changes the check to compare the password plaintext and ignore the username. The check is slower than the direct hash …
=> enhancement: Warn if (and only if) using the default admin password

docs/modules/policies/pages/compile.adoc, docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.20.0.adoc
=> chore(release): Add 0.20.0 release notes

api/genpb/cerbos/engine/v1/hashpb_helpers.pb.go, api/genpb/cerbos/runtime/v1/hashpb_helpers.pb.go, api/private/buf.lock
=> chore(deps): Private API buf mod update

internal/engine/planner.go, internal/engine/testdata/ast_build_expr.yaml, internal/test/testdata/query_planner/policies/principal_policy_macros.yaml, internal/test/testdata/query_planner/suite/macro_user.yaml
=> fix: Query planner partially evaluates a lambda body

internal/test/e2e/tests.go
The client has a default retry timeout of 2 seconds that seems
insufficient inside the GitHub runner. This is probably because the
runner is under-powered.
=> chore(test): Increase client timeout in E2E tests

docs/modules/configuration/partials/fullconfiguration.adoc, internal/server/conf.go, internal/server/server.go, internal/server/server_test.go
Add options to configure server settings such as keepalive timeouts and
request size limits.
=> enhancement: Advanced server configuration

go.mod, go.sum
=> chore(deps): Update go.opentelemetry.io/otel/bridge/opencensus to 0.32.1

.github/workflows/vulnerability-check.yaml
=> chore(ci): Run Go vulnerability check periodically

Dockerfile.cerbos, Dockerfile.cerbosctl
=> chore(deps): Update alpine base image from 3.15 to 3.16

docs/modules/policies/pages/authoring_tips.adoc, docs/modules/policies/pages/scoped_policies.adoc
=> docs: Make optionality of Scoped Policies more explicit

docs/modules/policies/pages/authoring_tips.adoc, docs/modules/policies/pages/scoped_policies.adoc
=> docs(backport): Make optionality of Scoped Policies more explicit (#1251)

docs/antora.yml, docs/modules/engineering/assets/images/organisation.png, docs/modules/engineering/nav.adoc, docs/modules/engineering/pages/index.adoc, docs/modules/engineering/pages/why_cerbos_runs_as_a_separate_process.adoc
=> docs(backport): Added `Engineering` section with post on single process usage (#1264)

internal/conditions/cerbos_lib.go, internal/engine/planner_test.go, internal/test/testdata/query_planner/policies/resource_policy_report_with_map.yaml, internal/test/testdata/query_planner/suite/report_with_map.yaml
Update remaining list functions to support partial evaluation for the query planner.
=> feat: Update list functions to support partial eval

README.md
Updating the logos of companies that openly use Cerbos.
=> docs: Updating the logos

client/model.go, client/model_test.go
=> fix(sdk): Missing setters in policy builders

docs/modules/ROOT/pages/tutorial/02_resource-definition.adoc
=> docs: Fix formatting of table in tutorial

docs/modules/ROOT/pages/tutorial/02_resource-definition.adoc
=> docs(backport): Fix formatting of table in tutorial

docs/modules/configuration/pages/storage.adoc, docs/modules/configuration/partials/cerbosctl.adoc
Also includes a note about ongoing issue with Azure DevOps.
=> docs: Add tip about using cerbosctl to load policies

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.22.0.adoc
=> chore(release): Add 0.22.0 release notes

docs/modules/recipes/nav.adoc
=> docs: Add recipe link to admin API demo

internal/audit/conf_test.go, internal/audit/file/log.go, internal/audit/file/log_test.go, internal/audit/local/badgerdb.go, internal/audit/local/badgerdb_test.go, internal/audit/log.go, internal/svc/admin_svc.go
=> enhancement: Clearer errors when trying to query audit logs

client/client.go
=> fix(sdk): Set scope of the plan resources request

.gitattributes, .github/workflows/pr-test.yaml, client/model.go, cmd/cerbosctl/put/internal/files/find.go, cmd/cerbosctl/put/internal/files/found.go, cmd/cerbosctl/put/policy.go, cmd/cerbosctl/put/schema.go, cmd/cerbosctl/put_test.go, cmd/cerbosctl/testdata/store.zip, docs/modules/cli/pages/cerbosctl.adoc, internal/util/filesystem.go
=> enhancement: Support zip files in cerbosctl put

internal/conditions/cerbos_lib.go, internal/engine/planner/ast.go, internal/engine/planner/internal/utils.go, internal/engine/planner/matchers/struct_matcher.go, internal/engine/planner/planner.go, internal/engine/planner/planner_test.go, internal/test/testdata/query_planner/policies/derived_roles/workspace.yaml, internal/test/testdata/query_planner/policies/resource_policy_report_with_map.yaml, internal/test/testdata/query_planner/suite/report_with_map.yaml, internal/test/testdata/query_planner/suite/report_with_map_admin.yaml
=> fix(planner): Known resource attribute as an index into a struct

internal/engine/planner/matchers/struct_matcher.go, internal/engine/planner/matchers/struct_matcher_test.go, internal/engine/planner/planner.go, internal/test/testdata/query_planner/suite/report_with_map.yaml, internal/test/testdata/query_planner/suite/report_with_map_admin.yaml
Optimize membership test expression having index into a struct: `"ADMIN" in P.attr.roles[R.attr.location_id]`
=> enhancement(planner): Optimize membership test expression having index into struct

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.23.0.adoc
=> chore(release): Add 0.23.0 release notes

.github/renovate.json
=> chore(ci): Disable Renovate go.mod Go version update

internal/engine/planner/matchers/struct_matcher.go
Fixes #1360 
Signed-off-by: Dennis Buduev <dbuduev@users.noreply.github.com>
=> fix: Flaky query plan test

internal/engine/planner/planner.go, internal/test/testdata/query_planner/policies/resource_policy_basics.yaml, internal/test/testdata/query_planner/suite/basics.yaml
Fixes #1370 
Signed-off-by: Dennis Buduev [dbuduev@users.noreply.github.com](mailto:dbuduev@users.noreply.github.com)
=> fix(planner): R.id unresolved

internal/engine/planner/planner.go, internal/test/testdata/query_planner/policies/resource_policy_basics.yaml, internal/test/testdata/query_planner/suite/basics.yaml
Backport of #1371 to 0.23 branch
=> fix(planner): R.id unresolved (#1371)

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.23.1.adoc
=> chore(release): Add 0.23.1 release notes

deploy/charts/cerbos/Chart.yaml, docs/antora-playbook.yml, docs/antora.yml, docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.23.1.adoc
Add release notes and bump version.
=> chore(release): Prepare v0.23.1 release

docs/modules/ROOT/examples/quickstart/example.java, docs/modules/policies/examples/curl.txt, docs/modules/policies/examples/example.cs, docs/modules/policies/examples/example.go, docs/modules/policies/examples/example.java, docs/modules/policies/examples/example.js, docs/modules/policies/examples/example.php, docs/modules/policies/examples/example.py, docs/modules/policies/examples/example.rb, docs/modules/policies/examples/example.rs, docs/modules/policies/nav.adoc, docs/modules/policies/pages/authoring_tips.adoc, docs/modules/policies/pages/best_practices.adoc, docs/modules/policies/pages/conditions.adoc
Backport of #1361 
Co-authored-by: Charith Ellawala <charithe@users.noreply.github.com>
=> docs(backport): Add policy best practices section (#1361)

docs/modules/recipes/nav.adoc, docs/modules/recipes/pages/orm/prisma/index.adoc, docs/modules/recipes/pages/orm/sqlalchemy/index.adoc
=> docs: Port SQLAlchemy integration guide from blog to docs

docs/modules/recipes/nav.adoc, docs/modules/recipes/pages/orm/prisma/index.adoc, docs/modules/recipes/pages/orm/sqlalchemy/index.adoc
=> docs(backport): Port SQLAlchemy integration guide from blog to docs (#1378)

docs/modules/recipes/pages/orm/prisma/index.adoc
Backport of #1386 
* Add section on ORM adapter
=> docs(backport): Update Prisma recipe to bring in line with demo repo (#1386)

.github/workflows/codeql.yml
Signed-off-by: Charith Ellawala <charithe@users.noreply.github.com>
=> chore(ci): Add CodeQL analyzer

internal/observability/logging/logging.go, internal/observability/logging/signal.go, internal/observability/logging/signal_windows.go
=> fix: Fix handling of the SIGUSR1 on Windows

go.mod, internal/storage/db/internal/funcs.go, internal/storage/db/internal/funcs_test.go, internal/storage/db/mysql/mysql.go, internal/storage/db/postgres/postgres.go, internal/storage/db/sqlite3/sqlite3.go, internal/storage/db/sqlserver/sqlserver.go
=> enhancement: Add wrapper function for `sqlx.Connect` call, incorporating basic retries

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.24.0.adoc
=> chore(release): Add 0.24.0 release notes

hack/notice/overrides/licences/github.com/pjbgf/sha1cd/LICENSE
=> chore: Add licence file for pjbgf/sha1cd

docs/modules/policies/pages/compile.adoc
=> docs: Add policyVersion example to tests

docs/modules/configuration/pages/storage.adoc
=> docs: Clarify how to provide blob store credentials

docs/modules/configuration/pages/storage.adoc
=> docs(backport): Clarify how to provide blob store credentials (#1433)

docs/modules/policies/pages/compile.adoc
=> docs(backport): Add policyVersion example to tests (#1430)

.github/workflows/e2e.yaml, .github/workflows/pr-test.yaml, .github/workflows/release.yaml, .github/workflows/snaphot.yaml, .github/workflows/test-matrix.yaml, .github/workflows/vulnerability-check.yaml, client/client_test.go, cmd/cerbosctl/audit/audit.go, cmd/cerbosctl/decisions/decisions.go, internal/conditions/cerbos_lib_benchmarks_test.go, internal/engine/planner/ast.go, internal/printer/printer.go
=> chore(ci): Use Go 1.20 in CI

docs/modules/policies/pages/best_practices.adoc
=> docs: Add note on resource-led policy design in `Best practices` section

client/admin.go
Adds missing RPCs;
- `DeleteSchema`
resolves #1455
=> enhancement: Add DeleteSchema RPC to the SDK AdminClient

docs/modules/api/pages/index.adoc
=> docs: Document /api/server_info

docs/modules/api/pages/index.adoc
=> docs(backport): Document /api/server_info (#1469)

docs/modules/ROOT/examples/tutorial/05-testing-policies/cerbos/tests/company_test.yaml, docs/modules/ROOT/examples/tutorial/05-testing-policies/cerbos/tests/contact_test.yaml
=> docs(backport): Add resource ID to test examples (#1488)

docs/modules/configuration/pages/audit.adoc, docs/modules/configuration/partials/fullconfiguration.adoc, internal/audit/kafka/conf.go, internal/audit/kafka/publisher.go
Document the Kafka audit backend.
=> docs: Add Kafka audit backend docs

.github/workflows/cache.yaml, .github/workflows/codeql.yml, .github/workflows/docs.yaml, .github/workflows/e2e.yaml, .github/workflows/pr-test.yaml, .github/workflows/pr-title.yaml, .github/workflows/release.yaml, .github/workflows/snapshot.yaml, .github/workflows/vulnerability-check.yaml
Set the workflow job timeouts explicitly.
=> chore(ci): Add timeouts to workflows

internal/audit/file/log.go
Calling `Sync` on stdout/stderr on Linux raises an error that can be
ignored. See https://github.com/uber-go/zap/issues/328.
Fixes #1514
=> chore: Ignore stdout/stderr sync errors in audit log

docs/modules/configuration/pages/audit.adoc, docs/modules/configuration/partials/fullconfiguration.adoc, go.mod, go.sum, internal/audit/kafka/conf.go, internal/audit/kafka/integration_test.go, internal/audit/kafka/kafka_test.go, internal/audit/kafka/publisher.go
Fixes the `context canceled` audit log message when producing via the async mechanism.
I've first committed some integration tests to show `sync` working, followed by `async` failing. The second commit then shows that async test is passing.
Fixes: https://github.com/cerbos/cerbos/issues/1504
=> fix: Kafka async produce context cancellation

internal/test/testdata/verify_junit/cases/case_001.yaml.golden, internal/test/testdata/verify_junit/cases/case_003.yaml.golden, internal/test/testdata/verify_junit/cases/case_004.yaml.golden, internal/verify/junit/junit.go
=> enhancement: Add principal, resource and action as properties of JUnit output

.github/workflows/release.yaml, .github/workflows/snapshot.yaml, api/private/buf.lock, api/private/buf.yaml, api/public/buf.lock, schema/jsonschema/cerbos/engine/v1/PlanResourcesAst.schema.json, schema/jsonschema/cerbos/engine/v1/PlanResourcesAst/LogicalOperation.schema.json, schema/jsonschema/cerbos/engine/v1/PlanResourcesAst/Node.schema.json
Publish the private, unstable proto definitions to BSR.
=> chore: Publish unstable API to BSR

docs/modules/cli/pages/cerbos.adoc, docs/modules/configuration/pages/storage.adoc, docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.26.0.adoc
=> chore(release): Add 0.26.0 release notes

docs/modules/policies/pages/best_practices.adoc, docs/modules/policies/pages/compile.adoc
=> docs: Clarify policy repository layout

docs/modules/policies/pages/best_practices.adoc, docs/modules/policies/pages/compile.adoc
=> docs(backport): Clarify policy repository layout (#1551)

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/feature.yaml, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md, .github/renovate.json
Some of the labels have been renamed for consistency.
=> chore(ci): Update Renovate labels

internal/server/server.go
Because `overlay.Store` implements `storage.BinaryStore`, it was incorrectly missing the `GetOverlayPolicyLoader` call and passing itself to the engine 🤦‍♂️ .
I picked this up when writing the E2E test - I'll add a (previously) failing test in that piece, but raising this now as a hot fix.
=> fix: Give `Overlay` interface precendence in storage switch on server startup

docs/modules/policies/pages/authoring_tips.adoc
=> docs(backport): Add paths to test schema files (#1564)

.github/actions/antora-docs/action.yaml, docs/build.sh
=> chore(deps): Update Antora to 3.1.2

docs/modules/cli/pages/cerbosctl.adoc
=> chore(docs): Fix referencing non-existent format flag

client/model.go, client/tests.go
SDK support for #1594
Fixes #1618
=> enhancement(sdk): Add support for user-defined outputs

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.27.0.adoc
=> chore(release): Add v0.27.0 release notes

deploy/charts/cerbos/templates/_helpers.tpl
=> enhancement(helm): Add config checksum to pod annotations so that deployment restarts on config changes

go.mod, go.sum
=> chore(deps): Update cloud-api to 0.1.4

docs/modules/ROOT/pages/tutorial/03_calling-cerbos.adoc
=> docs: Fix typo in 03_calling-cerbos.adoc

docs/modules/ROOT/pages/tutorial/03_calling-cerbos.adoc
This PR fixes a small typo in the docs.
Fixes #1727
=> fix(docs): Typo in Calling Cerbos

docs/modules/ROOT/examples/quickstart/example.cs, docs/modules/ROOT/examples/quickstart/example.php
=> docs(backport): Update SDK examples (#1731)

docs/modules/api/pages/index.adoc
This PR fixes wrong a wrong endpoint/rpc stated in the docs.
Fixes #1733
=> docs: Remove deprecated endpoint/rpc

docs/modules/configuration/pages/storage.adoc, docs/modules/configuration/partials/db_sync.adoc
=> docs(backport): Caveats of sharing a DB with multiple instances (#1743)

internal/storage/git/conf.go, internal/storage/git/store.go, internal/storage/git/store_test.go
=> fix: Normalize Git store subdirectory config to handle leading `./` correctly

docs/modules/policies/pages/authoring_tips.adoc, docs/modules/policies/pages/compile.adoc
Adds the testdata schema files to docs
=> docs: Add testdata schema URLs

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.30.0.adoc
=> chore(release): Add 0.30.0 release notes

Makefile, go.mod, go.sum
=> chore: Drop replace directive for API module

docs/modules/api/assets/images/laravel.svg, docs/modules/api/pages/index.adoc
=> chore(docs): Add link to Laravel SDK

docs/modules/api/pages/admin_api.adoc
=> docs: Remove unstable warning from Admin API

cmd/cerbos/server/server.go, deploy/charts/cerbos/values-bundle-storage.yaml, docs/modules/configuration/partials/fullconfiguration.adoc, docs/supplemental-ui/partials/header-content.hbs, hack/dev/conf.secure.bundle.yaml, internal/observability/metrics/metrics.go, internal/server/server_test.go, internal/storage/bundle/conf.go, internal/storage/bundle/conf_test.go, internal/storage/bundle/local_source.go, internal/storage/bundle/remote_source.go, internal/storage/bundle/remote_source_test.go, internal/telemetry/server_launch.go, internal/util/app.go
=> chore: Rename Cerbos Cloud to Cerbos Hub

go.mod, go.sum, internal/server/server.go
Automatically reload TLS certificates when they change on disk without
restarting the Cerbos server.
=> feat: Reload certificates when they change on disk

docs/modules/policies/pages/conditions.adoc, docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.31.0.adoc
=> chore(release): Add 0.31.0 release notes

internal/engine/engine.go, private/verify/verify.go
=> chore: Access to check options from custom checkers

docs/modules/configuration/pages/server.adoc
=> docs: Remove outdated playground section

docs/modules/configuration/pages/server.adoc
=> docs(backport): Remove outdated playground section (#1864)

.github/workflows/release.yaml, .github/workflows/snapshot.yaml, .goreleaser.yml, docs/modules/ROOT/pages/installation/container.adoc, docs/modules/ROOT/partials/attributes.adoc
=> enhancement(ci): Mirror Cerbos image to Docker Hub

internal/observability/tracing/tracing.go
When the legacy OTLP exporter is configured with the `tracing` block, we
need to create the exporter manually because the Otel library cannot
read our custom environment implementation to read the endpoint and
insecure configuration.
=> chore: Fix legacy OTLP exporter initialization

cmd/cerbosctl/get/get_test.go, cmd/cerbosctl/put/put_test.go
=> chore(test): Ignore source attributes in cerbosctl tests

.github/actions/antora-docs/action.yaml, docs/antora-playbook.yml, docs/build.sh, docs/modules/ROOT/examples/tutorial/03-resource-definition/cerbos/policies/company.yaml, docs/modules/ROOT/examples/tutorial/03-resource-definition/cerbos/policies/contact.yaml, hack/scripts/prep-release.sh
=> docs: Fix incorrect policy rule in tutorial

README.md
=> chore(docs): Readme update

docs/build.sh, docs/modules/policies/pages/variables.adoc
Updates the documentation to show how to assign string and array literals to policy variables.
=> docs: Add policy variable examples

netlify.toml
Fix the redirect rules to make images render correctly for all versions.
=> docs: Fix image URLs

docs/modules/ROOT/partials/attributes.adoc
=> docs(backport): Add old version warning banner

netlify.toml
This reverts commit 5072b9314b16cb99d153f1ee38bf8dfd3b00e48f.
=> chore: Revert "docs: Fix image URLs (#1943)"

internal/protoyaml/protoyaml.go, internal/test/testdata/protoyaml/case_008.json, internal/test/testdata/protoyaml/case_008.json.input, internal/test/testdata/protoyaml/case_012.json, internal/test/testdata/protoyaml/case_012.json.input, internal/test/testdata/protoyaml/case_013.json, internal/test/testdata/protoyaml/case_013.json.input, internal/test/testdata/protoyaml/case_014.json, internal/test/testdata/protoyaml/case_014.json.input, internal/test/testdata/protoyaml/case_015.json, internal/test/testdata/protoyaml/case_015.json.input
Test cases for parsing JSON files
=> chore: Add JSON test cases for parser

.github/workflows/pr-test.yaml, deploy/charts/validate.sh
Adds helm charts validation to the CI.
Fixes #
https://github.com/cerbos/cerbos/issues/1549
=> enhancement(ci): Validate Helm chart in CI

.github/workflows/release.yaml, .goreleaser.yml
Signs release artifacts:
- binaries
- docker images
Fixes #
https://github.com/cerbos/cerbos/issues/239
=> enhancement(ci): Sign release artifacts

.github/workflows/snapshot.yaml
=> chore(ci): Add cosign to snapshot build job

docs/supplemental-ui/partials/header-content.hbs
Add top nav links for Cerbos PDP and Cerbos Hub
=> chore(docs): Update header to have tabs for PDP and Hub

internal/verify/test_fixture.go, internal/verify/verify.go, internal/verify/verify_test.go, private/verify/verify.go
Allow selecting test particular resources and principals. Private API only.
=> feat: Add tests filtering

.github/actions/setup-go/action.yaml, .github/workflows/pr-test.yaml, internal/test/testdata/.jsonschema/ProtoYamlTestCase.schema.json, internal/test/testdata/.jsonschema/ServerTestCase.schema.json, schema/jsonschema/cerbos/policy/v1/DerivedRoles.schema.json, schema/jsonschema/cerbos/policy/v1/ExportVariables.schema.json, schema/jsonschema/cerbos/policy/v1/Policy.schema.json, schema/jsonschema/cerbos/policy/v1/PrincipalPolicy.schema.json, schema/jsonschema/cerbos/policy/v1/PrincipalRule.schema.json, schema/jsonschema/cerbos/policy/v1/PrincipalRule/Action.schema.json, schema/jsonschema/cerbos/policy/v1/ResourcePolicy.schema.json, schema/jsonschema/cerbos/policy/v1/ResourceRule.schema.json, schema/jsonschema/cerbos/policy/v1/RoleDef.schema.json, schema/jsonschema/cerbos/policy/v1/Variables.schema.json, schema/jsonschema/cerbos/request/v1/AddOrUpdatePolicyRequest.schema.json, schema/jsonschema/cerbos/request/v1/ListAuditLogEntriesRequest.schema.json, schema/jsonschema/cerbos/response/v1/GetPolicyResponse.schema.json
=> chore: Use Go 1.22

cmd/cerbos/repl/internal/repl.go
Print error location and details when loading invalid policy files in
the REPL.
=> enhancement: Detailed load errors in REPL

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.34.0.adoc
=> chore(release): Add 0.34.0 release notes

CONTRIBUTING.md
=> docs: Fix Go version in CONTRIBUTING.md

docs/modules/configuration/pages/index.adoc, docs/modules/configuration/pages/server.adoc, docs/modules/deployment/nav.adoc, docs/modules/deployment/pages/cloud-platforms.adoc
=> docs(backport): Add fly.io deploy guide (#2039)

docs/modules/recipes/pages/authentication/aws-cognito/index.adoc, docs/modules/recipes/pages/authentication/fusionauth/index.adoc, docs/modules/recipes/pages/authentication/okta/index.adoc
=> docs: Embed tutorial videos

docs/supplemental-ui/css/site-extra.css
=> docs(backport): Improve documentation accessibility (#2069)

docs/antora-playbook.yml, docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.35.0.adoc, hack/scripts/prep-release.sh
=> chore(release): Add 0.35.0 release notes

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.35.1.adoc
=> chore(release): Add 0.35.1 release notes

docs/modules/ROOT/pages/installation/binary.adoc, docs/modules/ROOT/pages/installation/container.adoc
=> docs: Document how to verify cosign signatures

docs/modules/ROOT/pages/installation/binary.adoc, docs/modules/ROOT/pages/installation/container.adoc
=> docs(backport): Document how to verify cosign signatures (#2094)

docs/modules/policies/pages/compile.adoc
=> docs: Add documentation for Dagger Cerbos module

docs/modules/policies/pages/compile.adoc
=> docs(backport): Add documentation for Dagger Cerbos module (#2106)

cmd/cerbosctl/inspect/inspect.go, cmd/cerbosctl/inspect/internal/flagset/filter.go, cmd/cerbosctl/inspect/internal/flagset/format.go, cmd/cerbosctl/inspect/policies.go, cmd/cerbosctl/root/root.go, docs/modules/cli/pages/cerbosctl.adoc, go.mod, go.sum
```
POLICY ID                                       ACTIONS              
resource.leave_request.vdefault                 *,create,submit,view    
resource.leave_request.vdefault/regional        *,create,submit,view    
principal.donald_duck.v20210210                 create,delete 
```
=> feat: Add cerbosctl inspect policies command

docs/modules/policies/pages/compile.adoc, internal/test/testdata/verify/cases/case_019.yaml, internal/test/testdata/verify/cases/case_019.yaml.golden, internal/test/testdata/verify/cases/case_019.yaml.input, internal/verify/test_fixture.go
Fixes https://github.com/cerbos/cerbos/issues/2115
=> fix: Default expectation to `EFFECT_DENY` for unspecified actions in tests

docs/modules/ROOT/assets/images/try_cerbos_hub.png, docs/modules/ROOT/partials/try-cerbos-hub.adoc, docs/modules/configuration/images/cerbos_hub.svg, docs/modules/configuration/pages/audit.adoc, docs/modules/configuration/pages/storage.adoc
- Add links to Hub documentation for Hub features.
- Sort storage drivers and audit backends by name.
=> docs: Document Hub features

.github/workflows/pr-test.yaml
=> chore(ci): Increase timeout for npm build stage

docs/modules/configuration/pages/storage.adoc, internal/storage/git/conf.go, internal/storage/git/conf_test.go
=> enhancement: Ensure git protocol matches the URL

cmd/cerbos/repl/internal/directive.go, cmd/cerbos/repl/internal/repl.go, cmd/cerbos/repl/internal/repl_test.go, cmd/cerbos/repl/repl.go
There are two commits here, but one is a simple one liner.
- fix `:load` with a plain filename, these were rejected by the parser as they were treated as identifiers
- adds some autocomplete support for `:` directives:
- `:...` get completed with directives
- `:load` completes filenames
- `:let` completes variables
- `:exec` completes rule numbers
=> feat(repl): Autocomplete for REPL directives, and a small fix for filenames

docs/modules/api/pages/admin_api.adoc, docs/modules/deployment/nav.adoc, docs/modules/deployment/pages/index.adoc, docs/modules/deployment/pages/k8s-daemonset.adoc, docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.37.0.adoc
=> chore(release): Add 0.37.0 release notes

.github/workflows/pr-test.yaml
=> chore(ci): Enable PR check for feature branches

internal/audit/hub/hub.go
=> chore: Add details to audit sync errors

internal/audit/hub/hub.go
=> chore: Trace logs for log sync

.github/workflows/aws.yaml, .github/workflows/release.yaml, .github/workflows/snapshot.yaml, .goreleaser.yml, .justfile, cmd/cerbos/server/server.go, go.mod, go.sum, internal/integrations/integrations.go
Build and publish a special container that calls the AWS usage API when launched.
=> chore(ci): Add ECR to release destinations

.github/workflows/release.yaml, .github/workflows/snapshot.yaml, .goreleaser.yml
=> enhancement(ci): Generate SBOMs for release artifacts

go.mod, go.sum, internal/storage/hub/remote_source.go, internal/storage/hub/remote_source_test.go
Requires https://github.com/cerbos/cloud-api/pull/177
=> feat: Allow Hub storage driver to connect to playgrounds

internal/audit/hub/hub.go, internal/audit/hub/hub_test.go
When there are decision log filters in place, there are no items to
delete from the local sync cache. The code wasn't handling that case
correctly.
=> fix: Handle empty decision entries during sync

internal/hub/hub.go
=> chore: Wrap credential validation error

internal/audit/hub/conf.go, internal/audit/local/badgerdb.go
Tweak settings to reduce memory usage at rest.
=> chore: Tune Badger settings

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.38.0.adoc
=> chore(release): Add 0.38.0 release notes

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.38.1.adoc
=> chore(release): Add 0.38.1 release notes

.goreleaser.yml, docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.38.1.adoc
Backport updates made for 0.38.1
=> chore: Backport 0.38.1 changes

deploy/charts/cerbos/Chart.yaml, docs/antora-playbook.yml, docs/antora.yml, netlify.toml, npm/packages/cerbos-darwin-arm64/package.json, npm/packages/cerbos-darwin-x64/package.json, npm/packages/cerbos-linux-arm64/package.json, npm/packages/cerbos-linux-x64/package.json, npm/packages/cerbos/package.json, npm/packages/cerbosctl-darwin-arm64/package.json, npm/packages/cerbosctl-darwin-x64/package.json, npm/packages/cerbosctl-linux-arm64/package.json, npm/packages/cerbosctl-linux-x64/package.json, npm/packages/cerbosctl/package.json
Backport release commit to v0.38 branch
=> chore(release): Prepare release 0.38.1

.github/workflows/pr-test.yaml
=> chore(ci): Clear disk space on PR run

.github/workflows/cache.yaml
=> chore(ci): Clear disk space for cache workflow

.github/workflows/vulnerability-check.yaml
=> chore(ci): Clear disk space for vulnerability check

docs/modules/ROOT/partials/attributes.adoc, docs/modules/deployment/pages/cloud-platforms.adoc
Add documentation for running Cerbos in EKS and ECS - needs to be merged once the product is published.
=> chore(docs): Add AWS Marketplace

docs/modules/ROOT/partials/attributes.adoc, docs/modules/deployment/pages/cloud-platforms.adoc
Backport be6f9e28664f829fe2e485188b070b6c1be08579
=> chore(docs): Backport AWS Marketplace docs

docs/modules/ROOT/pages/installation/helm.adoc
PAT should be the password as per https://docs.cerbos.dev/cerbos/latest/configuration/storage#git-driver
=> fix(docs): Update Helm doc

internal/schema/schema.go
We construct a logger with the incoming payload and pass it to the
validate function where it's only ever used if validation fails. For
large payloads, this adds a noticeable cost. Furthermore, because the
error message already includes object paths, it's not necessary to log
the original payload as well.
=> enhancement: Remove eager log initialisation from schema validation

internal/observability/metrics/metrics.go, internal/storage/blob/store.go, internal/storage/db/internal/db.go, internal/storage/disk/dirwatch.go, internal/storage/disk/disk.go, internal/storage/git/store.go, internal/storage/hub/remote_source.go
=> enhancement: Change how blob storage creates work directories and add metric for the last store refresh

internal/storage/blob/cloner_test.go, internal/storage/blob/store.go, internal/storage/blob/store_test.go
=> enhancement: Keep cached files under base64 encoded directory for blob storage

schema/schema.go
Fixes [Unable to obtain the HTTP Schema of the reverse proxy](https://github.com/cerbos/cerbos/issues/2299)
=> fix(schema): Support TLS with reverse proxy

docs/modules/ROOT/pages/installation/binary.adoc
=> docs: Document the Cerbos Nix flake

docs/modules/deployment/pages/cloud-platforms.adoc
Updates to AWS Marketplace documentation.
=> chore(docs): Reference payment via AWS Marketplace

docs/modules/deployment/pages/cloud-platforms.adoc
Updates to AWS Marketplace documentation.
---------
Fixes #
=> docs(backport): Reference payment via AWS Marketplace (#2322)

docs/modules/policies/pages/role_policies.adoc, docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.39.0.adoc
=> chore(release): Add 0.39.0 release notes

internal/storage/db/sqlserver/sqlserver_test.go
The SQL Server container is quite flaky and the tests fail randomly due
to problems starting the container. This PR skips the SQL Server tests
if the container fails to start.
=> chore(test): Skip SQL Server tests when container fails

internal/test/testdata/verify/cases/case_036.yaml, internal/test/testdata/verify/cases/case_036.yaml.golden, internal/test/testdata/verify/cases/case_036.yaml.input, internal/verify/run_test_suite.go
Closes https://github.com/cerbos/cerbos/issues/1486
=> enhancement!: Report an error if a test exercised time-based policy conditions without specifying `now`

e2e/run.sh
=> chore(ci): Increase E2E test timeout

docs/modules/deployment/pages/cloud-platforms.adoc
Uses the Helm chart published to ECR
=> chore(docs): Update AWS Helm docs

docs/modules/deployment/pages/cloud-platforms.adoc
Uses the Helm chart published to ECR
Fixes #
=> chore(backport):Update AWS Helm docs (#2372)

go.mod, go.sum
=> chore(deps): Use latest cloud-api and protobufs

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.40.0.adoc
=> chore(release): Add 0.40.0 release notes

docs/modules/policies/pages/best_practices.adoc
The PR cerbos/cerbos#1327 optimizes what we describe in the section.
=> chore(docs): Remove map of relations section from the best practises page

docs/modules/policies/pages/best_practices.adoc
=> backport(docs): Remove map of relations section from the best practises page (#2399)

docs/modules/ROOT/pages/what-is-cerbos.adoc
tenet : a principle, belief, or doctrine generally held to be true
especially : one held in common by members of an organization, movement, or profession
tenant : one who has the occupation or temporary possession of lands or tenements of another
specifically : one who rents or leases a dwelling (such as a house) from a landlord
Fixes #
=> docs: Update what-is-cerbos.adoc tenant ->tenet

private/policy/policy.go
=> chore: Add read function to private package

npm/test/cases/npm@11/.npmrc, npm/test/cases/npm@11/package.json, npm/test/cases/pnpm@10/.npmrc, npm/test/cases/pnpm@10/package.json
This PR adds the latest versions of npm and pnpm to the test cases.
=> chore: Test against npm v11 and pnpm v10

internal/engine/ruletable/rule_table.go
This was supposed to be part of the [larger PR](https://github.com/cerbos/cerbos/pull/2460) but I forgot to push it 🙃.
=> chore: Small optimisation in rule table lazy load

internal/conditions/cel.go, internal/engine/planner/planner.go, internal/test/testdata/query_planner/policies/resource_policies/expense.yaml, internal/test/testdata/query_planner/suite/expense.yaml
A resource or principal scope values can be used in the conditions, so their values should be used in the plan.
=> feat(plan): Use scope value in the query plan

docs/modules/policies/nav.adoc, docs/modules/policies/pages/principal_policies.adoc, docs/modules/policies/pages/resource_policies.adoc, docs/modules/policies/pages/role_policies.adoc, docs/modules/policies/pages/scope_permissions.adoc, docs/modules/policies/pages/scoped_policies.adoc
Would appreciate any feedback. It makes sense to me, but it might not to anyone else, so please be brutal.
=> docs: Scope permissions

go.mod, go.sum, internal/policy/io.go, internal/server/server.go, internal/validator/validator.go
=> chore: Use global protovalidate Validator

docs/modules/recipes/pages/orm/prisma/index.adoc
Update the Prisma guide to use the updated adapter which has a slightly different interface
=> chore(docs): Update Prisma guide to use v2.0

docs/modules/policies/pages/conditions.adoc, docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.41.0.adoc
=> chore(release): Add 0.41.0 release notes

docs/modules/configuration/examples/sqlserver_schema.sql
=> docs: Remove symlink to SQL Server schema

docs/modules/configuration/examples/sqlserver_schema.sql
=> docs(backport): Remove symlink to SQL Server schema (#2505)

internal/printer/printer.go
=> chore: Handle kind ROLE in trace printer

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.42.0.adoc
=> chore(release): Add 0.42.0 release notes

.github/workflows/pr-test.yaml, .github/workflows/snapshot.yaml
=> chore(ci): Make Coveralls upload optional

deploy/charts/cerbos/values-otlp.yaml
=> fix(helm): Set correct environment variable to configure traces sampler

internal/engine/planner/planner.go, internal/svc/cerbos_svc.go
Restore the backwards compatibility of the planner decision logs.
=> fix(plan): Preserve action field for auditing

docs/supplemental-ui/partials/header-content.hbs
Add a link to book a workshop to the header
=> docs: Add talk to engineer link

internal/engine/planner/planner.go
The scenario in https://github.com/cerbos/cerbos/issues/2577 arises because of the usage of `roles` as arguments in conditions. We end up with numerous equivalent logical nodes which are (in this case) OR'd together. Ensuring we avoid any unnecessary logical ops on equivalent nodes solve this.
=> chore: Deduplicate logical nodes in planner output

api/genpb/cerbos/policy/v1/policy.pb.go, api/public/cerbos/policy/v1/policy.proto
Missed these in #2595 :facepalm:
=> chore: More ASCII character class replacements

.github/workflows/pr-test.yaml, .github/workflows/release.yaml, .github/workflows/snapshot.yaml
https://github.com/bufbuild/buf-action/blob/main/MIGRATION.md
=> chore(ci): Remove deprecated `buf` actions

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.45.0.adoc
=> chore(release): Add 0.45.0 release notes

.github/workflows/release.yaml, .github/workflows/snapshot.yaml
https://github.com/bufbuild/buf-action/issues/76
=> chore(ci): Fix `buf push` step

docs/antora-playbook.yml, docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.45.1.adoc
=> chore(release): Add 0.45.1 release notes

docs/supplemental-ui/css/site-extra.css
Prevent the white background on logo hover
=> docs: Fix css for logo on hover

cmd/cerbosctl/internal/flagset/global.go, go.mod, go.sum, internal/server/codec.go
=> chore: Enable gzip and increase response size limit for cerbosctl

hack/dev/dev.mk
=> chore: Use new Bitnami repository

docs/modules/releases/nav.adoc, docs/modules/releases/pages/v0.46.0.adoc
=> chore(release): Add 0.46.0 release notes

README.md
Correcting a broken link
Fixes #
=> docs: Fix broken link in README.md

internal/storage/hub/conf.go, internal/storage/hub/remote_source.go, internal/storage/hub/remote_source_test.go
Add option to disable fetching bootstrap bundles.
=> chore: Config option to disable bootstrapping
