cerbos/cerbos

docs/antora-playbook.yml

Antora's default redirect page adds a `no-index` directive to the source
which makes the Googlebot ignore it. This patch changes the redirect
strategy to use Netlify redirects -- which are pure 301s.

chore: Change docs redirect

---

docs/supplemental-ui/css/site-extra.css
docs/supplemental-ui/partials/footer-content.hbs
docs/supplemental-ui/partials/head-meta.hbs
docs/supplemental-ui/partials/header-content.hbs

Add [Algolia DocSearch](https://docsearch.algolia.com) to the header of
the docs site.
Site configuration is available here:
https://github.com/algolia/docsearch-configs/blob/master/configs/cerbos.json

docs: Add Algolia DocSearch

---

.github/dependabot.yml
.github/workflows/release.yaml
.github/workflows/snaphot.yaml

- Update the buf-push-action to use latest bugfix. (See
https://github.com/bufbuild/buf-push-action/issues/4)
- Configure buf-push-action to publish the public API only.
- Update jobs to use the official Docker login action.

chore(ci): Update Buf push action

---

NOTICE.txt
client/client_test.go
go.mod
internal/server/server.go
internal/server/server_test.go

Adds h2c (http/2 cleartext) support to the http server endpoint so that
gRPC requests can be sent to the http endpoint even when TLS is not
enabled.

enhancement: Support h2c

---

docs/modules/cli/nav.adoc
docs/modules/cli/pages/ctl.adoc

Unfortunately, documentation update for the `cerbosctl` split slipped
through the net. This PR fixes references to `cerbos ctl` with `cerbosctl`.

docs: Update references to cerbosctl

---

hack/scripts/prep-release.sh

During a release, Antora should be instructed to build the `main` branch
instead of `HEAD`. This is because `HEAD` points to the current tag and
Antora has already built that tag during its tag discovery phase. This
duplication causes the build to fail.

chore(ci): Toggle docs author mode during release

---

internal/storage/disk/index/builder.go
internal/test/testdata/index/intermingled_test_files.yaml
internal/util/filesystem.go
internal/verify/test_fixture.go
internal/verify/test_fixture_test.go
internal/verify/verify.go
internal/verify/verify_test.go

Ignore test files and testdata when looking for policies

enhancement: Allow intermingling of tests with policies

---

internal/codegen/rego.go
internal/storage/db/internal/db.go
internal/storage/disk/index/builder_test.go
internal/test/testdata/codegen/valid_resource_policy_03.yaml
internal/test/testdata/store/derived_roles/derived_roles_01.yaml
internal/test/testdata/store/derived_roles/derived_roles_02.yaml
internal/test/testdata/store/resource_policies/policy_01.yaml

When multiple derived roles are imported, only the last set is "active"
within the policy execution environment. This is because the Rego import
statements override each other.
This PR fixes the above problem by merging all imports together
explicitly.
Also fixes an issue with the DB driver where multiple imports were not
getting stored correctly in the table.
Fixes #329

bug: Preserve all imported derived roles during execution

---

internal/server/conf.go

By mistake, the config key to _disable_ CORS is actually called
`cors.enabled`. This change renames the config key to the correct usage
of `cors.disabled`.
Fixes #333

bug: Rename cors.enabled config key to cors.disabled

---

NOTICE.txt
go.mod
go.sum

chore(deps): Bump github.com/containerd/containerd from 1.5.5 to 1.5.7

---

docs/modules/policies/pages/conditions.adoc
internal/conditions/cerbos_lib_test.go
internal/conditions/types/hierarchy.go
internal/test/testdata/cel_eval/hierarchy_funcs.yaml

- Allow specifying an optional delimiter when converting a string to a
hierarchy.
- Allow converting string arrays to a hierarchy
- Add `overlaps` method to check whether one hierarchy is a prefix of
the other
Fixes #328

enhancement: Hierarchy function improvements

---

docs/modules/ROOT/partials/attributes.adoc
internal/test/test.go

Updates documentation to specify correct URL to download Cerbos binaries.
Fixes #421

fix: Updates URL to download Cerbos binaries

---

.github/semantic.yml

The default prefixes don't include "enhancement" which is an important
distinction to make when producing release notes.

chore(ci): Configure semantic commit prefixes

---

docs/modules/configuration/pages/index.adoc

Fixes `passwordHash` parameter not being base64 encoded in the full configuration section of the configuration docs.
Fixes #431

docs: Fix passwordHash in full configuration doc

---

.github/workflows/pr-test.yaml

Configures the PR workflow to run for backport PRs raised against v* branches

chore(ci): Run PR workflow for backports

---

hack/scripts/prep-release.sh

Updates the Antora branch list to replace `HEAD` with `main` during a
release. This is because docs are now built from branches. If the
release tag tries to build `HEAD` it will clash with the version from
the corresponding release branch.

chore(ci): Update docs branch list during release

---

NOTICE.txt
go.mod
go.sum

chore(deps): Bump github.com/opencontainers/image-spec from 1.0.1 to 1.0.2

---

client/model.go

- Update the client SDK to make it easy to check for validation errors
- Remove redundant `toStructPB` method

enhancement: Update SDK to make validation errors accessible

---

NOTICE.txt
go.mod
go.sum

chore(deps): Bump github.com/opencontainers/runc from 1.0.2 to 1.0.3

---

internal/policy/policy.go
internal/schema/schema.go
internal/schema/schema_test.go
internal/storage/blob/cloner.go
internal/storage/store.go

- Blob store clone was always failing due to a potential issue with the
upstream library
- Schema cache was using the wrong key and not updating itself correctly
while processing storage events

chore: Fix schema cache and blob store timeout

---

internal/svc/admin_svc.go

List policies were returning the error message in case some error happens internally. This PR makes list policies not return the error message but only log it.
Fixes #480

chore(refactor): Fix list policies endpoint returning error message

---

.github/dependabot.yml

AWS SDK gets updated very frequently and most of the updates are not relevant to us

chore(ci): Disable patch version updates for AWS SDK

---

docs/supplemental-ui/partials/footer-content.hbs
docs/supplemental-ui/partials/head-meta.hbs
docs/supplemental-ui/partials/header-content.hbs

Algolia is deprecating DocSearch v2. 
https://docsearch.algolia.com/docs/DocSearch-v3

docs: Upgrade to DocSearch v3

---

go.mod

There should be two `require` directives only: one for direct dependencies, and another one for indirect dependencies.
Fixes #528

chore: tidy `go.mod` correctly

---

.golangci.yaml
client/credentials.go
internal/storage/store.go

- Enable `gomoddirectives` to catch accidental `replace` directives
- Enable `wastedassign` to catch wasted assignments

chore(lint): Enable more linters

---

Dockerfile

The Distroless base image uses some packages from Debian that have
vulnerabilities: https://github.com/GoogleContainerTools/distroless/issues/886
Even though we don't use the affected library in any way (CGO is disabled),
container image scans would still report the problem.
The fix is only available in [Debian Sid and Bookworm](https://security-tracker.debian.org/tracker/CVE-2021-33574)
but Distroless still has not migrated to those versions of Debian.
Since both upstream projects are moving very slowly, we'll just have to
address the issue ourselves. This PR switches the base image to
`scratch` and uses the CA certificates from Alpine. I have tested the
new image with GitHub and GCS and there were no issues establishing the
TLS connections.
Security scan reveals no issues either:
``` …
```

enhancement: Switch from Distroless to scratch

---

internal/server/server.go

Do not ignore unknown fields when parsing incoming JSON requests.

enhancement: Strict JSON request parsing

---

internal/engine/ast.go
internal/test/testdata/query_planner/policies/resource_policy.yaml
internal/test/testdata/query_planner/suite/adam.yaml

Handle the case when the query plan produces a nil filter because
there's nothing to filter on.
Not a "proper bug" because this feature is not yet released.

chore(bug): Handle case when query plan filter is nil

---

.github/workflows/e2e.yaml
e2e/README.md
e2e/kind.yaml
e2e/run.sh

Add a GitHub workflow to run E2E tests. This is still experimental
because Telepresence doesn't seem to play nice inside a container.

chore(ci): Add workflow to run E2E tests

---

.github/workflows/e2e.yaml
e2e/blob/blob_test.go
e2e/git/git_test.go
e2e/mysql/mysql_test.go
e2e/postgres/postgres_test.go
e2e/run.sh
e2e/sqlite/sqlite_test.go
internal/server/server_test.go
internal/server/tests.go
internal/test/e2e/tests.go

- Run E2E tests every weekday at 1 am
- Increase timeout for tests because Kind on GH Actions is slow
- Add query planner suite to the suites list
- Make tests fail fast to avoid wasting time on subsequent tests
- Reduce parallelism to 2

chore(ci): Run E2E tests on schedule

---

internal/server/server_test.go

Server tests didn't work inside GH Actions before. Checking to see whether that's still the case.

chore(ci): Enable server tests in CI

---

docs/modules/api/pages/index.adoc

Describes the format of the query plan response with a list of possible
operators and some examples of ASTs.
The CEL-specific operators such as `loop`, `loop-accu-init` etc. have
been omitted from the list for the moment but they should be documented
with examples in a future PR.
These docs assume that the changes made in #558 have been merged.

docs: Document the query plan response

---

docs/modules/configuration/examples/sqlserver_schema.sql
docs/modules/configuration/pages/storage.adoc
docs/modules/configuration/partials/fullconfiguration.adoc
go.mod
go.sum
internal/server/server.go
internal/storage/db/internal/db.go
internal/storage/db/internal/db_opts.go
internal/storage/db/internal/funcs.go
internal/storage/db/internal/funcs_test.go
internal/storage/db/mysql/mysql_test.go
internal/storage/db/sqlserver/conf.go
internal/storage/db/sqlserver/schema.sql
internal/storage/db/sqlserver/sqlserver.go
internal/storage/db/sqlserver/sqlserver_test.go

Adds SQL Server as a cerbos policies storage.

feat: Add SQL Server support

---

e2e/mysql/helmfile.yaml
e2e/postgres/helmfile.yaml

Fixes dangling quotes in Postgres and MySQL helmfiles serving E2E tests.

fix: Dangling quotes in helmfiles

---

docs/modules/ROOT/pages/index.adoc

Backport of #587 to v0.12 (latest) docs

docs(backport): Add service model explanation (#587)

---

cmd/cerbosctl/cerbosctl_test.go
cmd/cerbosctl/get/internal/policy/policy.go
cmd/cerbosctl/internal/print.go

fix: cerbosctl get subcommands retrieve unmatching policy types

---

docs/modules/tutorials/assets/images/fusionauth-add-roles.png
docs/modules/tutorials/assets/images/fusionauth-application-form.png
docs/modules/tutorials/assets/images/fusionauth-application-listing.png
docs/modules/tutorials/assets/images/fusionauth-dashboard-applications.png
docs/modules/tutorials/assets/images/fusionauth-video.png
docs/modules/tutorials/assets/images/okta-app-settings.png
docs/modules/tutorials/assets/images/okta-create-app.png
docs/modules/tutorials/assets/images/okta-groups-claim.png
docs/modules/tutorials/assets/images/okta-video.png
docs/modules/tutorials/nav.adoc
docs/modules/tutorials/pages/authentication/auth0/index.adoc
docs/modules/tutorials/pages/authentication/fusionauth/index.adoc
docs/modules/tutorials/pages/authentication/okta/index.adoc

Add in the missing Okta and FusionAuth tutorials to the docs site.

docs:Add Okta & FusionAuth tutorials

---

api/genpb/cerbos/private/v1/hashpb_helpers.pb.go
api/genpb/cerbos/request/v1/hashpb_helpers.pb.go
api/genpb/cerbos/response/v1/hashpb_helpers.pb.go

Because #607 was merged before #597, the generated protobuf code is not up-to-date on main

chore: Update generated code

---

.github/workflows/docs.yaml
.github/workflows/pr-test.yaml
.github/workflows/pr-title.yaml
.github/workflows/snaphot.yaml

- Use a GitHub action to perform the conventional commit check because
the Semantic app has been flaky recently. GH Actions can also be
restarted unlike the app.
- Add path filters to avoid running jobs unnecessarily. For example,
don't run tests if only docs have changed.

chore(ci): Replace conventional commit check

---

.github/workflows/e2e.yaml
.github/workflows/pr-title.yaml

Last two failures were due to a trafficManagerAPI timeout which defaults to 15s
Also updates the conventional commit check because it's unhappy with the regex.

chore(ci): Increase Telepresence timeout for E2E tests

---

internal/namer/namer.go
internal/namer/namer_test.go
internal/policy/policy_test.go
internal/storage/blob/cloner_test.go
internal/storage/db/internal/tests.go
internal/storage/index/builder_test.go
internal/test/testdata/compile/multiple_imports.yaml.golden
internal/test/testdata/compile/only_derived_roles.yaml.golden
internal/test/testdata/compile/principal_policy.yaml.golden
internal/test/testdata/compile/scoped_pp_missing_ancestor.yaml
internal/test/testdata/compile/scoped_principal_policy_set.yaml
internal/test/testdata/compile/scoped_principal_policy_set.yaml.golden
internal/test/testdata/compile/scoped_resource_policy_set.yaml
internal/test/testdata/compile/scoped_resource_policy_set.yaml.golden
internal/test/testdata/compile/scoped_rp_missing_ancestor.yaml
internal/test/testdata/compile/simple_valid_policy_set.yaml.golden
internal/test/testdata/engine/case_06.yaml
internal/test/testdata/index/disabled_ancestor.yaml
internal/test/testdata/index/duplicate_scoped_policies.yaml
internal/test/testdata/index/valid_files.yaml
internal/test/testdata/server/admin/add_or_update_policy/case_00.yaml
internal/test/testdata/server/checks/check_resource_set/crs_case_06.yaml
internal/test/testdata/server/playground/proxy/pgp_crb_case_02.yaml
internal/test/testdata/server/playground/proxy/pgp_crs_case_03.yaml
internal/test/testdata/store/principal_policies/policy_02.yaml
internal/test/testdata/store/resource_policies/policy_05.yaml

Makes no-scope policies the root of the tree when evaluating scoped policies.
```mermaid
stateDiagram-v2
state "resource.leave_request.vdefault/acme.corp" as grandchild
state "resource.leave_request.vdefault/acme" as child
state "resource.leave_request.vdefault" as parent
[*] --> grandchild
grandchild --> child
child --> parent
parent --> [*]
``` 

enhancement: Make no-scope policy the root of the tree

---

cmd/cerbosctl/cerbosctl_test.go
cmd/cerbosctl/get/internal/policy/filter.go
cmd/cerbosctl/get/internal/policy/filter_test.go
cmd/cerbosctl/get/internal/policy/policy.go
cmd/cerbosctl/get/internal/policy/print.go
internal/compile/compile.go
internal/compile/errors.go
internal/policy/policy.go
internal/storage/db/internal/db.go
internal/storage/db/sqlserver/sqlserver.go
internal/storage/index/builder.go
internal/storage/index/index.go
internal/storage/subscriptionmgr.go

- Add scope column to `cerbosctl` get output
- Refactor filter code to avoid an extra slice allocation
- Refactor `policy.Wrapper` to avoid unnecessarily computing dependencies 

enhancement: Add scope to cerbosctl output

---

.golangci.yaml
Makefile
internal/conditions/cerbos_lib.go

I accidentally introduced a formatting error in #670, but CI didn't catch it. The golangci-lint GitHub Action does not override the `fix` setting from the config file, so when auto-fixable linter issues are found in CI they were fixed and not reported. This PR switches to using the `--fix` flag in the Makefile instead.

chore(ci): Fix linter issues when running `make lint`, but not in CI

---

hack/loadtest/conf/grafana/dashboards/cerbos.json
hack/loadtest/docker-compose.yml
hack/loadtest/genres.go
hack/loadtest/k6/check.js
hack/loadtest/loadtest.sh
internal/observability/metrics/metrics.go
internal/server/server.go
internal/storage/index/builder.go
internal/storage/index/index.go

- Add a metric to report the number of entries in the index.
- Update Grafana dashboard to report Cerbos internals.
- Tweak load test scripts.

enhancement: Add index entry count metric

---

docs/modules/policies/pages/compile.adoc

This PR removes spurious trailing commas from YAML in the "Testing policies" section of the docs.

docs: Fix YAML syntax in testing documentation

---

.goreleaser.yml

Relates to https://github.com/cerbos/homebrew-tap/issues/1, see also https://github.com/cerbos/homebrew-tap/pull/2
This PR updates the GoReleaser configuration to generate the `cerbos` Homebrew formula in the `Formula` subdirectory of https://github.com/cerbos/homebrew-tap. Currently, it's being generated in the root of the tap repository, and `brew install` is picking up the older version from the `Formula` directory.

fix: Configure GoReleaser to generate Homebrew formula in tap's `Formula` subdirectory

---

hack/loadtest/README.md
hack/loadtest/check.js
hack/loadtest/loadtest.sh

As we didn't have a sensible approach to add policies using Admin API to the `postgres` store, the support for load testing with `postgres` store was not complete. With the addition of `cerbosctl put` command, we are able to put policies or schemas into the store. This PR fixes this issue and now we are able to load test using `postgres` store.

chore(test): Add support for load testing with the postgres store

---

Dockerfile
cmd/cerbos/healthcheck/healthcheck.go
cmd/cerbos/healthcheck/healthcheck_test.go
cmd/cerbos/main.go
cmd/cerbos/server/server.go
docs/modules/cli/pages/cerbos.adoc

Adds a `healthcheck` subcommand to the `cerbos` binary so that
in-container healthchecks (Docker HEALTHCHECK) can be performed without
resorting to an external binary.
Fixes #666

feat: Add healthcheck command

---

docs/modules/policies/pages/derived_roles.adoc
docs/modules/policies/pages/principal_policies.adoc
docs/modules/policies/pages/resource_policies.adoc

If I land directly on https://docs.cerbos.dev/cerbos/latest/policies/resource_policies.html (either coming via Google, deep-linking, or navigating through the sidebar), I don't get any context before diving into the YAML syntax.
This PR resolves that by copying the contextual information from the policies index page down to the child pages (we might consider expanding on it but for now it's better than nothing!).

docs: Add context to policy documentation

---

docs/modules/tutorials/examples/photo-share/tests/album_object_test.yaml
docs/modules/tutorials/pages/photo-share/index.adoc

Update the test definitions in the photo-share tutorial to match the new
changes introduced by #701.

docs: Update photo-share tutorial tests

---

internal/test/testdata/verify/invalid_fixture/testdata/principals.yaml
internal/test/testdata/verify/invalid_test/did_not_expected_key_test.yaml
internal/verify/test_fixture.go
internal/verify/verify.go
internal/verify/verify_test.go

Fixes #723 
This PR calls `Validate` on the values read from test suite and fixture files, so that the rules specified in the proto message definition are enforced.

fix: Validate that test files match schema

---

hack/loadtest/generate.go

When generating data for the load tests, the output directories are deleted and recreated. This was flaky because the map iteration order is non-deterministic, meaning we could delete `policies` after recreating `policies/_schemas` (resulting in `no such file or directory` errors when generating schemas).

chore(test): Handle non-deterministic ordering of output directory deletion

---

.github/workflows/dependabot.yaml
.github/workflows/e2e.yaml
.github/workflows/pr-test.yaml
.github/workflows/release.yaml
.github/workflows/snaphot.yaml
.github/workflows/test-matrix.yaml

Note that this only upgrades CI workflows to use Go 1.18. The minimum Go
version in `go.mod` is still `1.17` because we don't use any new Go 1.18
features yet. Using the new Go compiler should still bring some of the
performance improvements to the builds. (20% improvement on ARM64
allegedly)

chore(ci): Upgrade to Go 1.18 on CI

---

cmd/cerbos/compile/compile.go
cmd/cerbos/compile/internal/compilation/display.go
cmd/cerbos/compile/internal/lint/display.go
cmd/cerbos/compile/internal/verification/display.go
cmd/cerbos/main.go
go.mod
internal/outputcolor/level.go
internal/outputcolor/level_test.go
internal/printer/printer.go

Fixes #752 (the color level is now set for `pterm` as well as the `color` library, so `--no-color` turns off all coloring in the tree output)
Fixes #753 
This PR introduces a complimentary `--color` flag in addition to the existing `--no-color`.
With the default of `--color=auto`, the output color level is detected from the environment by checking if stdout is a TTY and looking for various environment variables (see https://pkg.go.dev/github.com/jwalton/go-supportscolor for details).
Otherwise, the output color level is set to:
- none for `--no-color`, `--color=false`, or `--color=never`;
- basic for `--color`, `--color=true`, or `--color=always`;
- 256-color for `--color=256`; and
- truecolor for `--color=16m`, `--color=full`, or `--color=truecolor`
This is basically a translation of …

enhancement: Add `--color` flag to `cerbos compile`

---

hack/tools/protoc-gen-jsonschema/module/enum.go
hack/tools/protoc-gen-jsonschema/module/module.go
schema/jsonschema/cerbos/policy/v1/Policy.schema.json
schema/jsonschema/cerbos/policy/v1/PrincipalPolicy.schema.json
schema/jsonschema/cerbos/policy/v1/PrincipalRule.schema.json
schema/jsonschema/cerbos/policy/v1/ResourcePolicy.schema.json
schema/jsonschema/cerbos/policy/v1/ResourceRule.schema.json
schema/jsonschema/cerbos/private/v1/CodeGenTestCase.schema.json
schema/jsonschema/cerbos/private/v1/CompileTestCase.schema.json
schema/jsonschema/cerbos/private/v1/ServerTestCase.schema.json
schema/jsonschema/cerbos/request/v1/AddOrUpdatePolicyRequest.schema.json
schema/jsonschema/cerbos/request/v1/ListAuditLogEntriesRequest.schema.json
schema/jsonschema/cerbos/response/v1/GetPolicyResponse.schema.json
tools/tools.mk

In protoc-gen-jsonschema, when `enum.*` validation rules are detected, use those rules to determine the allowed set of enum values.
Also makes the base URL for schemas configurable.
Fixes #766

chore(fix): Restrict set of JSON schema enums to match validation rule

---

.github/workflows/pr-test.yaml

As of #768 we check backwards compatibility against the latest release version instead of against the main branch. This is good because it allows us to make backwards-incompatible changes against unreleased features, but it does mean that if we deliberately introduce a breaking change in one PR (e.g. #775) then all subsequent PRs will fail the check until the breaking change is released.
This PR uses [a fork of buf-breaking-action](https://github.com/cerbos/buf-breaking-action/tree/since) to allow us to find breaking changes against the previous release, but then filter out ones that were introduced in previous PRs. The earlier breaking changes will be included in the CI logs but not annotated on the proto files.

chore(ci): Only report newly-introduced backwards-compatibility breakage

---

.github/workflows/release.yaml

I didn't realise that by default `gsutil rsync` doesn't delete files from the target that aren't present in the source - we need the `-d` flag to ensure that the `latest` directory exactly matches the `vX.Y.Z` directory.

chore(ci): Delete JSON schemas from latest when removed in a release

---

.github/ISSUE_TEMPLATE/bug.yaml
.golangci.yaml
CONTRIBUTING.md
Makefile
go.mod
hack/tools/protoc-gen-jsonschema/go.mod
tools/go.mod

chore: Set minimum Go version to 1.18

---

internal/test/testdata/policy_formats/derived_roles_01.yaml
internal/test/testdata/policy_formats/principal_policy_01.yaml
internal/test/testdata/policy_formats/resource_policy_01.yaml
internal/util/serdeio.go

If the first line of the YAML file contains a comment, the
multiple-document detector incorrectly classifies the file as containing
more than one YAML document and fails. This patch fixes that issue.

fix: Handle comments at the beginning of YAML files

---

go.mod
go.sum
internal/server/middleware.go
internal/server/tests.go

Replace the Gorilla CORS handler with rs/cors because it is easier to
configure (allows wildcards for allowed headers) and has debugging
built in.

chore: Replace CORS handler

---

.github/workflows/release.yaml

The `DOWNLOAD_GCS_BUCKET` secret is expected to have the `gs://` prefix
but the `API_GCS_BUCKET` does not. This change updates the action to add
the `gs://` prefix to the `DOWNLOAD_GCS_BUCKET` to keep things
consistent.

chore(ci): Use the same format for GCS buckets

---

.goreleaser.yml

Group the commits by their type in the changelog shown in the GitHub
releases page.

chore: Group changelog items

---

cmd/cerbos/repl/internal/directive_test.go
cmd/cerbos/repl/internal/repl.go
cmd/cerbos/repl/internal/repl_test.go

Adds support for correctly handling variables declared in the policy file.
Variables are re-evaluated each time any of the inputs change.

enhancement: Policy variables in the REPL

---

docs/modules/configuration/pages/server.adoc
docs/modules/policies/pages/conditions.adoc

- MacOS `base64` command does not require the `--wrap` argument.
- Explain that `bcrypt` output is not deterministic.
- Add a note about supported duration units in conditions

docs: Add MacOS command variant for password generation

---

.goreleaser.yml

Fixes the Gorelease changelog grouping.
Goreleaser uses the output from `git log` where each line begins with the commit hash and the regexes need to be updated to take that into consideration.
Fixes #887 

chore(ci): Update changelog grouping

---

internal/observability/tracing/tracing.go

The new version of Otel added by #885 uses a new version of the semantic
conventions (v1.10.0). We currently import v1.7.0 of semconv and that clashes with
the newer version -- preventing the server from starting up.

chore: Update Otel semconv version

---

hack/tools/confdocs/confdocs.go

fix(ci): Fix confdocs panicking when no comment for a struct provided

---

e2e/README.md

The repository for the `helmfile` project is changed from https://github.com/roboll/helmfile to https://github.com/helmfile/helmfile. This PR changes the URL in `e2e/README.md` to reflect this change.
There is still a reference to the old repository in `.github/workflows/e2e.yaml:36`, but since the new repository does not have a release yet we will have to wait for it. Created an issue (#913) for this.

chore(ci): Update README of the E2E tests to reflect the change of the helmfile repository

---

e2e/jaeger/helmfile.yaml
e2e/jaeger/jaeger_test.go

The issue in #905 wasn't caught early because tracing is initialised in
`main` which is not covered by unit tests. The E2E tests didn't catch it
either because tracing was disabled. This PR adds an E2E test that runs
with Jaeger tracing enabled so that we can catch similar issues in the
future.

chore(e2e): Add E2E test with tracing enabled

---

docs/modules/cli/pages/cerbosctl.adoc
docs/modules/configuration/pages/audit.adoc
docs/modules/configuration/partials/fullconfiguration.adoc
internal/audit/file/conf.go
internal/audit/file/log.go
internal/audit/file/log_test.go
internal/audit/log.go
internal/audit/log_test.go
internal/server/server.go
internal/svc/admin_svc.go

Adds a new audit log backend named `file` which simply writes log entries to a file (or stdout/stderr). That file can then be picked up by log aggregators for archival and querying.

feat: Add file backend for audit logs

---

docs/modules/api/pages/index.adoc

The limits on the lengths of the `resources` and `actions` request fields are currently undocumented.

docs: Document limits on `resources` and `actions`

---

docs/modules/api/pages/index.adoc

docs(backport): Document limits on `resources` and `actions` (#930)

---

docs/modules/configuration/pages/audit.adoc
docs/modules/configuration/partials/fullconfiguration.adoc
internal/audit/conf.go

Due to a change in how config is unmarshaled, the defaults are not
correctly being set. Until that issue is fixed, we need to update the
examples to instruct the users that they should explicitly set the
`accessLogsEnabled` and `decisionLogsEnabled` settings.

docs: Update audit examples

---

docs/modules/configuration/pages/audit.adoc
docs/modules/configuration/partials/fullconfiguration.adoc
internal/audit/conf.go

Due to a change in how config is unmarshaled, the defaults are not
correctly being set. Until that issue is fixed, we need to update the
examples to instruct the users that they should explicitly set the
`accessLogsEnabled` and `decisionLogsEnabled` settings.

docs(backport): Update audit examples (#950)

---

hack/dev/conf.insecure.yaml
hack/dev/conf.secure.yaml
hack/dev/plan.hurl
hack/dev/requests/plan_resources/req1.json
hack/dev/requests/plan_resources/req2.json
internal/audit/conf.go
internal/audit/conf_test.go

Audit conf needs to be parsed leniently (to ignore unknown fields) because it can have different backend configurations. Because of this, the `SetDefaults` method does not get called correctly -- resulting in the defaults for `accessLogsEnabled` and `decisionLogsEnabled` not being set.
This patch sets the defaults before unmarshaling to fix the above problem.

fix: Apply defaults when loading audit config

---

internal/conditions/cel.go
internal/conditions/cel_test.go
internal/engine/ast.go
internal/engine/planner_test.go
internal/test/testdata/query_planner/suite/harry.yaml
internal/test/testdata/query_planner/suite/macro_user.yaml
internal/test/testdata/query_planner/suite/maggie.yaml
internal/test/testdata/server/plan_resources/plan_case_01_acme.hr.uk.yaml
internal/test/testdata/server/plan_resources/plan_case_02_acme.hr.yaml

Expands aliases like `R` into their full form (`request.resource`) so
that regardless of the expression used in the policy, the PlanResources
output is always predictable.
Also implements some simple optimisations like converting `X && true`
into `X` or `X || false` into `false`.
Fixes #962
Fixes #874

enhancement: Expand aliases in PlanResources output

---

e2e/run.sh
internal/storage/blob/tests.go

The blob store tests have started failing because the new release of
Minio container is checking the data directory for IO-DIRECT access.
Switching to the default `/data` directory seems to fix this issue.
In addition, the healthcheck should be using the readiness probe instead
of the liveness probe because sometimes the server is not yet ready to
accept connections even if it is up.
Also reduces the parallelism in E2E test runs because lately they have
been failing -- possibly due to resource contention.

chore(test): Update Minio config in tests

---

docs/modules/configuration/pages/server.adoc
docs/modules/configuration/partials/fullconfiguration.adoc
internal/server/conf.go
internal/server/server.go
tools/go.mod
tools/go.sum

Allow the file mode of the Unix domain socket to be set by the user. By
default Go creates the socket with 0o766 which makes it unusable if the
client is running as a different user.

enhancement: Allow setting file mode of UDS

---

schema/openapiv2/cerbos/svc/v1/svc.swagger.json
tools/go.mod
tools/go.sum

This PR updates `protoc-gen-openapiv2` to pull in https://github.com/grpc-ecosystem/grpc-gateway/pull/2719 which fixes `google.protobuf.Value` having a `{ "type": "object" }` schema, when in fact it can be any JSON-serializable value and should have an empty schema `{}`.

fix: Handle `google.protobuf.Value` correctly in OpenAPI schemas

---

docs/modules/configuration/pages/tracing.adoc
go.mod
go.sum
internal/observability/tracing/conf.go
internal/observability/tracing/tracing.go
internal/server/server.go

Allows the HTTP server to automatically detect and handle traces
propagated using different formats. Supports trace-context, baggage and
b3 by default. Can be overridden using the OTEL_PROPAGATORS environment
variable.
Fixes #967

enhancement: Support auto-propagation for traces

---

.github/workflows/snaphot.yaml

Update the snapshots workflow to publish the new `cerbosctl` container
with the `dev` tag as well.

chore(ci): Publish cerbosctl snapshot container

---

docs/modules/api/assets/images/javascript.svg
docs/modules/api/pages/index.adoc

This PR replaces references to the old Node.js SDK with the new JavaScript one.
It also swaps the order of the logos and text so that they align neatly, and removes the `interactive` option from the SVGs so that the links work (when embedded as `<object>` elements with `interactive`, the surrounding `<a>` doesn't get cursor focus).

docs: Add new JavaScript SDK

---

internal/storage/git/store.go
internal/storage/git/store_test.go

Fixes #984 
The git store currently only ignores test files on the initial load - index updates attempt to read tests as policies, causing an unmarshalling error.
This PR ignores test files in index updates as well.

fix: Ignore test files when updating index from git

---

docs/modules/api/assets/images/javascript.svg
docs/modules/api/pages/index.adoc

Backports #986 to add the new JavaScript SDK to the v0.17 docs.

docs(backport): Add new JavaScript SDK (#986)

---

internal/observability/metrics/metrics.go
internal/storage/blob/store.go
internal/storage/db/internal/db.go
internal/storage/disk/dirwatch.go
internal/storage/git/store.go
internal/storage/index/index.go

Increments a counter each time a store is polled for updates and records
the success or failure status.
Also adds counters for CRUD operations.
Fixes #987

enhancement: Add store polling metrics

---

internal/storage/index/index.go
internal/storage/index/index_test.go
internal/storage/index/schema.go

The `ListSchemaIDs` method currently assumes that schemas are located in `./_schemas`, but the index's filesystem is not rooted at the policies directory.
This PR refactors the method to delegate to the `SchemaLoader`, which is aware of the policies directory set by `WithRootDir`.

fix: Respect `WithRootDir` option in `(Index).ListSchemaIDs`

---

.github/workflows/pr-test.yaml

We can shave ~25% off the CI execution time by running the generate and test steps in parallel.

chore(ci): Parallelize generate and test jobs

---

api/genpb/cerbos/private/v1/hashpb_helpers.pb.go
api/genpb/cerbos/private/v1/test.pb.go
api/genpb/cerbos/private/v1/test.pb.validate.go
api/genpb/cerbos/private/v1/test_hashpb.pb.go
api/genpb/cerbos/private/v1/test_vtproto.pb.go
api/private/cerbos/private/v1/test.proto
internal/engine/ast.go
internal/engine/planner.go
internal/engine/planner_test.go
internal/test/testdata/query_planner_filter/case_00.yaml
internal/test/testdata/query_planner_filter/case_01.yaml
internal/test/testdata/query_planner_filter/case_02.yaml
internal/test/testdata/query_planner_filter/case_03.yaml
internal/test/testdata/query_planner_filter/case_04.yaml
internal/test/testdata/query_planner_filter/case_05.yaml
internal/test/testdata/query_planner_filter/case_06.yaml
internal/test/testdata/query_planner_filter/case_07.yaml
internal/test/testdata/query_planner_filter/case_08.yaml
internal/test/testdata/query_planner_filter/case_09.yaml
internal/test/testdata/query_planner_filter/case_10.yaml
internal/test/testdata/query_planner_filter/case_11.yaml
internal/test/testdata/server/plan_resources/plan_case_00.yaml
internal/test/testdata/server/plan_resources/plan_case_01_acme.hr.uk.yaml
internal/test/testdata/server/plan_resources/plan_case_02_acme.hr.yaml
internal/test/testdata/server/playground/proxy/pgp_rqp_case_00.yaml

Generates the `filterDebug` field from the normalised filter instead of
the raw AST.
This change makes the `filterDebug` output a bit more abstract by
producing S-expressions instead of the more CEL-like output before. The
previous output wasn't pure CEL anyway, so this change shouldn't be too
disruptive.
Fixes #964

enhancement!: Normalise query plan filterDebug field

---

internal/engine/ast.go
internal/test/testdata/server/plan_resources/plan_case_00.yaml
internal/test/testdata/server/playground/proxy/pgp_rqp_case_00.yaml

I noticed a couple of test cases with redundant `(and x x)` clauses, thought it might be nice to optimise those out.

enhancement: Deduplicate operands to and/or operations

---

docs/modules/policies/pages/derived_roles.adoc

docs(backport): Use analogy to explain derived roles (#1015)

---

docs/modules/configuration/partials/fullconfiguration.adoc
go.mod
go.sum
internal/observability/tracing/conf.go
internal/observability/tracing/tracing.go

Currently, traces can only be exported in the Jaeger format, where as our collectors can only accept OTLP (gRPC or HTTP).
For the first PR I've kept the OTLP config simple by only supporting gRPC and no config to tune/enhance the exporter, such as gzip, load-balancing policy, batching or TLS.
**Issue:** #1018

enhancement: Export traces via OTLP to a collector

---

hack/tools/confdocs/confdocs.go

I have realized - thanks to #1017 (Thanks @rcrowe!) - `confdocs` doesn't have a check for empty struct tags, hence it is panicking.

chore(docs): Fix confdocs panic when no struct tag is provided

---

internal/engine/ast.go
internal/engine/ast_test.go
internal/engine/testdata/ast_build_expr.yaml
internal/test/testdata/query_planner/policies/resource_policy_leave_request.yaml
internal/test/testdata/query_planner/suite/harry.yaml

Membership test operation `in` can be used to test if a key exists in a map. 
The produced AST currently contains the entire struct, which is confusing. It is expected the map to be converted to a list of keys.

fix: Transform maps to lists for membership test  

---

cmd/cerbos/compile/compile.go
internal/storage/index/builder.go
internal/storage/index/index.go

Fixes #441 
When no more than 5 errors occur during index build, or when debug logging is enabled, the full error details will now be printed instead of just the summary.
e.g. when starting server the output is now
```
2022-06-21T10:59:32.594+0100    ERROR   cerbos.index    Index build failed      {"missing": [{"importingFile":"policy.yaml","desc":"Import 'wat' not found"}]}
cerbos: error: failed to create store: failed to build index: missing imports=1, missing scopes=0, duplicate definitions=0, load failures=0
```
or if more than 5 errors occur
```
2022-06-21T11:38:49.002+0100    ERROR   cerbos.index    Index build failed      {"error": "too many errors; run `cerbos compile` to see a full list"}
cerbos: error: failed to create store: failed to build index: missing imports=3, missing …
```

enhancement: Output detailed index build errors when the number of errors is low

---

internal/engine/ast.go
internal/engine/lambda.go
internal/engine/testdata/ast_build_expr.yaml
internal/test/testdata/query_planner/policies/resource_policy_leave_request.yaml
internal/test/testdata/query_planner/suite/harry.yaml

Expressions like `exists`, `all`, and `exists_one` can be applied to maps, but only map keys are used in the expressions. The resource plan API hence can contain a list instead of a map in the produced AST. That makes the AST much easier to parse.

fix: Transform maps to lists in comprehension expressions

---

internal/engine/engine_test.go
internal/engine/evaluator.go
internal/engine/evaluator_test.go
internal/test/testdata/cel_eval/missing_attr_allof.yaml
internal/test/testdata/cel_eval/missing_attr_anyof.yaml
internal/test/testdata/cel_eval/missing_attr_noneof.yaml
internal/test/testdata/server/playground/test/pgt_case_00.yaml

If a boolean expression arm in one of `any`, `all` or `none` blocks
uses a non-existent attribute, it returns a `nil` value. This cannot be
cast to a bool so we raise an error and short-circuit the evaluation of
the whole block. This patch fixes that issue.
Fixes #1055

fix: Avoid short-circuit when expressions access non-existent attributes

---

go.mod
go.sum
internal/conditions/cerbos_lib.go
internal/conditions/types/hierarchy.go

New CEL release deprecates `ProgramOption.Functions` in favour of
`EnvOption.Function`, which simplifies things by not requiring both
decls and overloads to be defined.
Fixes #1081

chore(refactor): Replace deprecated CEL options

---

.github/workflows/pr-title.yaml
hack/scripts/apply-pr-labels.sh

Fixes #773 
This PR adds a job to CI to apply label(s) to the PR depending on the Conventional Commits prefix in the title.
To avoid erroneously removing manually-applied labels, it doesn't attempt to remove labels, so if the prefix changes it might be necessary to manually remove outdated labels. I didn't feel like it was worth the extra complexity to attempt to remove labels because I don't think it's common for the prefix to swap between types.
I also removed `ci` and `test` from the allowed types, because we tend to use `chore(ci)` and `chore(test)` instead.

chore(ci): Use pull request title to apply labels

---

internal/conditions/cerbos_lib.go

Using `env.Extend` to override the time functions on every program is
expensive because it needs to copy the type registry.
This patch uses a decorator to rewrite calls to `now` and `timeSince`
with a timestamp captured at the start of the program.
Fixes #1123

enhancement: Use plan decorator to provide consistent time functions

---

netlify.toml

Netlify CLI is now behaving differently for some reason. The publish
directory needs to be changed to accommodate it.

chore(ci): Update Netlify conf

---

.github/workflows/e2e.yaml
e2e/run.sh

Telepresence now requires the traffic manager to be installed manually
by the user.
- Update E2E script to install Telepresence traffic manager
- Update workflow to use latest Helmfile release
Fixes #913

chore(test): Update E2E setup script

---

client/client_test.go
client/model.go

We have overlooked adding helpers to set the scope on principals and
resources when using the SDK.

fix(sdk): Allow setting scope on SDK requests

---

client/client_test.go
client/model.go

Backport of #1151 
We have overlooked adding helpers to set the scope on principals and
resources when using the SDK.

fix(backport): Allow setting scope on SDK requests

---

deploy/charts/cerbos/Chart.yaml
docs/antora-playbook.yml
docs/antora.yml
docs/modules/releases/nav.adoc
docs/modules/releases/pages/v0.19.1.adoc

Release 0.19.1 with the fix for setting scopes using the Go SDK.

chore(release): Prepare release 0.19.1

---

.github/workflows/pr-test.yaml

Netlify preview deploys don't work within a workflow because the command
tries to open a browser to authenticate even when the credentials are
provided in the environment.

chore(ci): Remove docs preview generation

---

internal/verify/test_fixture.go
internal/verify/verify.go
private/verify/verify.go

Allow passing engine implementation to the private verifier.

chore: Refactor private/verify package

---

docs/modules/policies/pages/derived_roles.adoc

I suggest to making more clear that parent roles are provided by the identity provider. It would be interesting to have some white papers links on the subject. Some libraries do this, such as alibaba (https://antv.vision/en/docs/specification/reference), but I couldn´t find any free white paper that talks about static roles and derived roles.
Signed-off-by: albcunha <albcunha@users.noreply.github.com>
Fixes #

docs: Add clarification about who provides parentRoles

---

docs/modules/configuration/partials/fullconfiguration.adoc
internal/audit/conf.go
internal/audit/interceptor.go
internal/audit/interceptor_test.go
internal/server/server.go

Adds `excludeMetadataKeys` and `includeMetadataKeys` to `audit` configuration.
```
audit:
accessLogsEnabled: true
excludeMetadataKeys: ['content-type', 'user-agent']
includeMetadataKeys: ['content-type', 'user-agent']
```
Here is description of how it works:
- If both `excludeMetadataKeys` and `includeMetadataKeys` has a certain key, the key will *NOT* be logged.
- If only `excludeMetadataKeys` has a certain key, the key will *NOT* be logged.
- If only `includeMetadataKeys` has a certain key, the key will be logged.
resolves #1201

enhancement: Allow specification of gRPC request metadata keys to be logged

---

docs/modules/policies/pages/derived_roles.adoc

Backport of #1207
I suggest to make more clear that parent roles are provided by the identity provider. It would be interesting to have some white papers links on the subject. Some libraries do this, such as alibaba (https://antv.vision/en/docs/specification/reference).
Signed-off-by: albcunha <albcunha@users.noreply.github.com>

docs(backport): Add clarification about who provides parentRoles (#1207)

---

docs/modules/configuration/pages/storage.adoc

Error:
```
2022-09-13T11:59:54.678+0300    ERROR   cerbos.git.store        Failed to initialize git store  {"dir": "...", "error": "failed to clone from ssh://github.com:cerbos/policy-test.git to ...: parse \"ssh://github.com:cerbos/policy-test.git\": invalid port \":cerbos\" after host"}
```

chore(docs): Fix git storage driver configuration example

---

client/client.go
client/client_test.go
client/tests.go
e2e/notls/helmfile.yaml
e2e/notls/notls_test.go
e2e/run.sh
internal/server/tests.go
internal/test/e2e/ctx.go
internal/test/e2e/tests.go

The SDK client was configured to use local transport credentials when the `WithPlaintext` option was used. That prevents the client from connecting to any hosts other than localhost. This PR switches the credential type to `insecure`.
We didn't catch this before because the E2E tests always use TLS. This PR integrates the client tests into the E2E suite and introduces a new test that runs without TLS.

fix(sdk): Allow plaintext connections to any host 

---

internal/compile/manager.go
internal/storage/db/internal/db.go
internal/storage/db/store.go
internal/storage/git/store.go
internal/storage/index/index.go
internal/storage/store.go

Purges the compile cache when the store is reloaded using the Admin API.
Previously, the cache was only updated when there were new or deleted
files. If an existing file had changed, that wasn't detected.
This change also makes the database stores reloadable.
Fixes #1215

fix: Purge compile cache on store reload

---

Makefile
internal/audit/interceptor.go
internal/compile/manager.go
internal/compile/manager_test.go
internal/engine/engine.go
internal/observability/tracing/attributes.go

Group simultaneous requests to compile a policy into a single call.
Also adds more trace spans to the engine to increase visibility.

enhancement: Group compile requests

---

docs/modules/policies/pages/conditions.adoc

The global `matches(string, string)` operator is deprecated from the CEL spec in favor of member syntax `x.matches(string)`.

docs: Fix usage of CEL matches operator

---

docs/modules/policies/pages/conditions.adoc

The global `matches(string, string)` operator is deprecated from the CEL spec in favor of member syntax `x.matches(string)`.

docs(backport): Fix usage of CEL matches operator (#1245)

---

deploy/charts/cerbos/templates/service.yaml
deploy/charts/cerbos/values.yaml

Add nodePort values in default values.yaml file to allow users to configure a custom NodePort
Fixes #1249

chore(helm): Allow configuring a custom nodePort in helm chart values

---

internal/engine/evaluator.go
internal/test/testdata/cel_eval/null_attr_allof.yaml
internal/test/testdata/cel_eval/null_attr_anyof.yaml
internal/test/testdata/cel_eval/null_attr_noneof.yaml

When evaluating `any`, `all` or `none` blocks, if one of the expressions
returns a non-boolean result, the whole block is marked as having
failed. We can be a bit more lenient here and treat non-boolean values
as `false`. Note that this treats _all_ values as `false` and does not
make the distinction of treating certain values as `true`. Users are
responsible for converting any non-boolean values into boolean values
themselves.

fix: Treat non-boolean expression results as `false`

---

.github/workflows/e2e.yaml
.github/workflows/pr-test.yaml
.github/workflows/release.yaml
.github/workflows/snaphot.yaml
.github/workflows/vulnerability-check.yaml

Force the `setup-go` action to check whether the cached Go version is
the latest.

chore(ci): Use latest Go version in builds

---

.github/workflows/pr-test.yaml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

chore(ci): Set output via environment file rather than stdout

---

internal/conditions/cerbos_lib.go
internal/engine/ast.go
internal/test/testdata/query_planner/policies/resource_policy_report_with_map.yaml
internal/test/testdata/query_planner/suite/report_with_map.yaml

Fixes #1276 
For the query planner the`hasIntersection` function needs to support partial evaluation.
I am going to update other functions in a separate PR(s).

fix: Update hasIntersection function to support partial eval

---

internal/test/testdata/query_planner/policies/resource_policy_hierarchy.yaml
internal/test/testdata/query_planner/suite/hierarchy_user.yaml
internal/test/testdata/query_planner/suite/maggie.yaml

Add a query planner test with some hierarchy functions.

chore: Confirm hierarchy funcs support partial eval

---

internal/engine/ast.go
internal/test/testdata/query_planner_filter/case_15.yaml

Adds optimisation for a query plan by replacing a membership test `in` with an equality check if the list contains a single item.  ` a in [x]` is replaced with `a == x`.
This supports the workaround for issue #1263.

feat: Optimise a query plan of a membership test in a single-item list

---

go.mod
internal/engine/ast.go

When generating the string representation of the query plan filter, we
use the `protojson` package to marshal some of the CEL protobufs.
Unfortunately, the output of `protojson` is not guaranteed to be stable
and the library intentionally adds random whitespaces to the output.
This PR strips non-essential whitespace from the JSON bytes to make the
output usable in tests.

chore: Stable string representation for query filter

---

.github/workflows/pr-title.yaml

GitHub no longer overwrites the squash commit title when there's only
one commit in a PR.

chore(ci): Remove single commit validation

---

internal/engine/planner/ast.go
internal/test/testdata/query_planner/policies/resource_policy_top.yaml
internal/test/testdata/query_planner/suite/wrong_attr_data_type.yaml
internal/test/testdata/query_planner_filter/case_16.yaml
internal/test/testdata/query_planner_filter/case_17.yaml
internal/test/testdata/query_planner_filter/case_18.yaml

When the query planner is trying to optimize an `IN` expression, it is
wrongly assuming that the operand can only be a list. This leads to the
planner completely ignoring IN expressions that don't have a list as an
operand.
This fix changes the logic to handle both lists and maps, which are valid
operand types to `IN`. Other non-container types cause the `IN` operator
to automatically convert itself to an `EQ`.
Fixes #1333

fix: Handle other data types while optimizing IN expression

---

Makefile

Disable CGO in the selected make targets for consistency with the goreleaser configuration.
Fixes #1326.

fix: Disable CGO for "compile" and "test" make targets

---

docs/modules/recipes/nav.adoc

Backport of #1338 
* Add recipe link to admin API demo
Co-authored-by: Charith Ellawala <charithe@users.noreply.github.com>

docs(backport): Add recipe link to admin API demo (#1338)

---

Makefile

Follow up to https://github.com/cerbos/cerbos/pull/1336.

chore: Disable CGO for "all" make target

---

docs/modules/configuration/pages/storage.adoc

Add a link to the Kubernetes git-sync repo as a potential workaround for
users of Azure DevOps.

docs: Add link to git-sync

---

docs/modules/configuration/pages/storage.adoc

Backport of #1344 
Add a link to the Kubernetes git-sync repo as a potential workaround for users of Azure DevOps.

docs(backport): Add link to git-sync (#1344)

---

go.mod
internal/observability/logging/logging.go

`atomic.Bool` is only available in Go 1.19 and users on older versions
of Go won't be able to download the SDK because of that. Since
`atomic.Bool` is not crucial for a correct implementation, we can revert
it this time.

fix: Rewrite log level change without Go 1.19 features

---

.github/workflows/snaphot.yaml

The tests introduced in #1343 require LFS objects.

chore(ci): Enable LFS for snapshot build

---

deploy/charts/cerbos/templates/_helpers.tpl
deploy/charts/cerbos/templates/deployment.yaml
deploy/charts/cerbos/templates/service.yaml
deploy/charts/cerbos/values-jaeger-agent.yaml
deploy/charts/cerbos/values.yaml

Allow users to define annotations for the deployment using
`deployment.annotations` value key and annotations for the service using
`service.annotations` value key.
Also adds `commonLabels` value key to help label all the resources
created by the chart.
Fixes #1362

enhancement(helm): Annotations for deployment and service

---

docs/modules/ROOT/pages/installation/binary.adoc

docs: Remove unstable warning from Linux packages

---

docs/modules/ROOT/pages/installation/binary.adoc

docs(backport): Remove unstable warning from Linux packages (#1368)

---

deploy/charts/cerbos/templates/_helpers.tpl
deploy/charts/cerbos/templates/deployment.yaml
deploy/charts/cerbos/templates/service.yaml
deploy/charts/cerbos/values-jaeger-agent.yaml
deploy/charts/cerbos/values.yaml

Backport of #1363 to 0.23 branch
Allow users to define annotations for the deployment using `deployment.annotations` value key and annotations for the service using `service.annotations` value key.
Also adds `commonLabels` value key to help label all the resources created by the chart.
Fixes #1362

enhancement(helm): Annotations for deployment and service (#1363)

---

docs/modules/configuration/pages/audit.adoc
docs/modules/configuration/partials/fullconfiguration.adoc
hack/dev/conf.secure.yaml
hack/dev/plan.hurl
hack/scripts/cover.sh
internal/audit/conf.go
internal/audit/decision_filter.go
internal/audit/decision_filter_test.go
internal/audit/file/log.go
internal/audit/file/log_test.go
internal/audit/local/badgerdb.go
internal/audit/local/badgerdb_test.go
internal/audit/log.go
internal/audit/metadata_test.go
internal/engine/engine_test.go

Adds ability to filter out some decision log entries from the audit log
to reduce noise.
- Ignore `CheckResources` reponses that have all `ALLOW` results
- Ignore all `PlanResources` responses
- Ignore `PlanResources` responses that are `ALWAYS_ALLOWED`
The implementation is intentionally asymmetric because the assumption
here is that `DENY` responses are inherently interesting and should not
be filtered out. Therefore, there are no options to log only `ALLOW`
responses.
Fixes #1380

feat: Support for filtering decision logs

---

e2e/git/helmfile.yaml
hack/dev/conf.secure.yaml

Exercise the recently added audit log filtering options in one of the
E2E test runs.

chore(test): Exercise audit log filtering in E2E tests

---

cmd/cerbosctl/put_test.go
internal/engine/engine.go
internal/storage/blob/cloner_test.go
internal/storage/index/builder_test.go
internal/test/testdata/engine/case_17.yaml
internal/test/testdata/store/principal_policies/policy_03.yaml

If there's only a principal policy and at least one of the actions does
not have a matching rule in the principal policy, everything gets denied
because we don't have a resource policy to fall back to. This PR fixes
that issue and preserves the valid decisions that came out of the
principal policy.
Fixes #1397

fix: Handle principal-policy-only cases

---

go.mod
go.sum
internal/storage/db/postgres/postgres.go
internal/storage/db/postgres/postgres_test.go

This reverts commit 349afb1df7b2fb9ba2d0d06575844a61f4cf55d5.

chore(deps): Revert update of github.com/jackc/pgx/v4 to v5 (#1425)

---

internal/compile/manager.go

Disabling policies trigger a recompilation, and during recompilation, we see the following error in the logs;
```
Processing storage event        {"event": "ADD/UPDATE [17261342906893367968]"}
cerbos.compiler Failed to recompile     {"id": {}, "error": "missing policy definition {17261342906893367968}: invalid compilation unit"}
```

fix: Evict disabled policy from the cache

---

docs/modules/configuration/partials/fullconfiguration.adoc
internal/compile/conf.go
internal/compile/manager.go
internal/storage/git/store.go
internal/storage/git/store_test.go
internal/storage/index/index.go
internal/storage/store.go

If a user edits a policy file in place and changes its identifiers
(name, version) then the old policy does not get evicted from the
compile cache and is still usable until Cerbos is restarted or the store
is reloaded using the Admin API.
This PR also adds a configuration field to set the expiry time of
compiled policies. The default is no expiry, which is the current
behaviour.

fix: Evict policies that are changed in-place

---

e2e/run.sh
internal/observability/tracing/tracing.go
internal/observability/tracing/tracing_test.go

The semconv package from Otel has a secondary version encoded in the
package name. So, even if the library version is updated in go.mod, we
have to remember to manually update the import path too. If not, it
panics because apparently two different "versions" of semconv cannot
co-exist together :shrug:
Did I mention that Otel is the worst library I have ever worked with?

chore: Upgrade Otel semconv version

---

internal/server/middleware.go
internal/server/server.go

This PR adds `cerbos-version` to the gRPC response headers (which comes through as `Grpc-Metadata-Cerbos-Version` in the HTTP response headers).

feat: Add Cerbos version to response headers

---

.github/actions/setup-go/action.yaml
.github/workflows/cache.yaml
.github/workflows/e2e.yaml
.github/workflows/pr-test.yaml
.github/workflows/release.yaml
.github/workflows/snapshot.yaml
.github/workflows/test-matrix.yaml
.github/workflows/vulnerability-check.yaml
Makefile

Since [branches don't share caches, except for the default branch](https://github.com/actions/cache#cache-scopes), we need to warm the cache on `main` branch pushes to avoid missing the cache on the first build of every PR.
Our caches are quite large, so to reduce eviction `pr-test` jobs now use common caches for dependencies and build outputs (generated by `make warm-cache`). The `snapshots` job re-uses the dependencies cache, but has a separate build cache which is much larger, thanks to cross-compiling.

chore(ci): Improve caching

---

.github/workflows/release.yaml
.github/workflows/snapshot.yaml
.goreleaser.yml
Dockerfile.cerbos
Makefile
cmd/cerbos/healthcheck/healthcheck.go
cmd/cerbos/server/server.go
docs/modules/configuration/pages/index.adoc
internal/config/conf.yaml.gotmpl
internal/config/config.go
internal/config/config_test.go
internal/storage/disk/disk.go

Make the `--config` flag optional for launching Cerbos. If it's not
specified and `CERBOS_CONFIG` environment variable is not set as well,
a default configuration is applied which sets the policy directory to
`${PWD}/policies`.
This is a breaking change for users who are using a container
orchestrator that uses Docker healthchecks (e.g. ECS) AND has mounted a
custom configuration file at `/conf.default.yaml` because the
container's `CERBOS_CONFIG` environment variable no longer points to it.
They should manually set the `CERBOS_CONFIG` environment variable as a
workaround. Unfortunately it's difficult to keep the old behaviour
without either duplicating the default configuration in two places or
breaking the `healthcheck` command.
Includes a couple of changes to fix deprecated settings in …

enhancement!: Make config flag optional

---

schema/assets/ui.html

Allow users to try out the Admin API with credentials.

enhancement: Enable auth on API explorer page

---

docs/modules/ROOT/pages/tutorial/04_testing-policies.adoc

Update 04_testing-policies.adoc
Minor typo fix.
Backport of #1477

docs(backport): Fix typo in 04_testing-policies.adoc (#1477)

---

docs/modules/policies/pages/compile.adoc

docs: Fix name of test output format flag

---

docs/modules/policies/pages/compile.adoc

docs(backport): Fix name of test output format flag (#1481)

---

.gitattributes
cmd/cerbos/compile/compile.go
cmd/cerbosctl/put/internal/files/find.go
docs/modules/configuration/pages/storage.adoc
go.mod
go.sum
internal/policy/policy.go
internal/storage/disk/disk.go
internal/storage/index/builder_test.go
internal/storage/index/index_test.go
internal/test/testdata/store_archive/policies.tar
internal/test/testdata/store_archive/policies.tgz
internal/test/testdata/store_archive/policies.zip
internal/util/filesystem.go
internal/util/filesystem_test.go

Adds function to attempt retrieval of an `fs.FS` instance from `tar`, `zip` and `gzip` files if they have the matching extensions, otherwise defaults to `os.DirFS`.
TODO

enhancement: Add support for reading archive files for the disk driver

---

internal/observability/tracing/tracing.go

In order to avoid schema conflicts every time Otel is upgraded, drop the
schema version from the resource definition. Since we are only using the
`ServiceName` attribute which ought to be stable by this point (but one
can never tell with Otel :shrug:), omitting the version should be fine.
https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v1.14.0/resource#Merge

chore: Make Otel resource schemaless

---

internal/audit/file/log.go
internal/audit/file/log_test.go
internal/audit/local/badgerdb.go
internal/audit/log.go
internal/server/server.go

As part of implementing [Kafka](https://github.com/cerbos/cerbos/pull/1499) I wanted to see when messages were failing to be flushed; async publishing and failing to flush can mean lost messages.
So as not to grow that PR & keep it focused, I've split this PR off.

enhancement: Report audit close error

---

.github/workflows/snapshot.yaml

Snapshot build takes longer than 20 minutes in some cases.

chore(ci): Increase snapshot build timeout

---

docs/modules/configuration/pages/audit.adoc
docs/modules/configuration/partials/fullconfiguration.adoc
internal/audit/kafka/conf.go
internal/audit/kafka/publisher.go

Attempts to fix this failure to publish async message to Kafka by ignoring the parent context cancelling within the async Kafka publishing.
```
{"log.level":"warn","@timestamp":"2023-03-30T20:57:20.147Z","log.logger":"cerbos.grpc","message":"failed to write audit log entry","grpc.start_time":"2023-03-30T20:57:20Z","system":"grpc","span.kind":"server","grpc.service":"cerbos.svc.v1.CerbosService","grpc.method":"CheckResources","cerbos":{"call_id":"01GWT4Z20J4ZJK0H74RQGXPJ36"},"peer.address":"@","error":"context canceled"}
```

fix: Kafka async publish fails when the API request returns

---

cmd/cerbos/server/server.go

The flag processor tries to convert the value of `CERBOS_CONFIG` into a
path and check whether it exists. Since we do that check while parsing
the config anyway, it can be disabled.

fix: Prevent default config from being turned into a path

---

internal/server/server_test.go

Fixes #1540 
Unix domain socket addresses are limited in length (generally) to 104-108, platform specific (on `MacOS Monterey 12.4`, this appears to be 104). Sometimes, the generation of the temp directory pathname (via `t.TempDir()`) can exceed this limit, so when attempting to create a uds listener, it would fail with `invalid argument`.
This PR creates a helper function with more explicit control over the length of the output pathname.

fix: Introduce custom temp directory creation function with pathname length limit for uds

---

Dockerfile.cerbos

Explicitly mark `/tmp` and `/.cache` as volumes so that the directories
are automatically created within the container.
Ideally `/tmp` should be a `tmpfs` mount and `/.cache` should be a
persistent mount, especially when the `bundle` driver is in use.

fix: Mark /tmp as a container volume

---

deploy/charts/cerbos/templates/_helpers.tpl
deploy/charts/cerbos/templates/deployment.yaml
deploy/charts/cerbos/values-bundle-storage.yaml

If the user is using the default settings, automatically mount
`emptyDir` volumes for temp and cache directories.
Also adds an example values file for connecting to Cerbos Cloud.

enhancement(helm): Volume mounts for Cerbos Cloud

---

internal/storage/index/builder.go
internal/test/testdata/index/schemas_in_valid_dir.yaml
internal/test/testdata/index/schemas_in_wrong_dir.yaml
internal/test/testdata/index/schemas_prepended_dir.yaml

enhancement: Handle schemas folder being in wrong place with more verbose error

---

.github/workflows/e2e.yaml

#1579 introduced a change which called `helmfile apply` instead of `helmfile sync`. The former requires `helm diff`, which was previously not installed on setup.

fix: Add `helmfile init` step to e2e GH actions setup

---

client/client.go
client/client_test.go
client/tests.go

fix: Use IncludeMetadata option on all gRPC requests

---

internal/compile/manager.go
internal/engine/engine.go
internal/svc/cerbos_svc.go

Instead of returning `Internal` error, return `FailedPrecondition` when
the requested policy has a compilation error. We already had this special case handled in the `CheckResourceSet` RPC but, for some reason, it had been omitted in the other RPCs.
Fixes #1590

fix: Return correct error code when store is invalid

---

internal/namer/namer.go
internal/test/testdata/server/checks/check_resources/cr_case_06.yaml
internal/test/testdata/server/checks/check_resources/cr_case_07.yaml

When we output metadata, we don't use the `cerbos.` prefix for the
policy name. To keep things consistent, the rule names in the policy
output should also drop the prefix.

chore: Remove the cerbos prefix from output keys

---

docs/modules/cli/pages/cerbosctl.adoc

docs(backport): Fix referencing non-existent format flag (#1617)

---

docs/modules/api/pages/index.adoc
docs/modules/policies/nav.adoc
docs/modules/policies/pages/outputs.adoc

Update the API response to include outputs and introduce a new page with
an example of how to use outputs.

docs: Add page with output example

---

internal/engine/tracer/context.go
internal/test/testdata/verify_junit/cases/case_007.yaml.golden
internal/verify/junit/junit.go

The engine trace sometimes displays the wrong condition in its ouput.
This is due to the underlying slice being reused inadvertantly.
Fixes #1635

fix: Render the condition correctly in an Engine trace

---

docs/modules/configuration/partials/fullconfiguration.adoc
internal/audit/kafka/conf.go
internal/audit/kafka/kafka_test.go
internal/audit/kafka/publisher.go

Adds support for different compression modes for kafka. We have a use case to use zstd and currently the franz-go package defaults to `snappy, none` (in priority order). 
Fixes #

feat: Support different compression algorithms for kafka audit

---

.github/workflows/e2e.yaml
e2e/run.sh
internal/server/tests.go
internal/test/e2e/setup.go
internal/test/e2e/tests.go

The latest spate of E2E failures with random timeouts seem to be related
to the new release of Telepresence. This PR pins the version of
Telepresence to the last-known good version.
This PR also includes a change to dump pod logs on test failure to help
with debugging.

chore(ci): Downgrade telepresence

---

cmd/cerbos/repl/internal/repl.go
cmd/cerbos/repl/internal/repl_test.go
cmd/cerbosctl/put_test.go
docs/modules/configuration/pages/engine.adoc
docs/modules/configuration/pages/index.adoc
docs/modules/configuration/partials/fullconfiguration.adoc
docs/modules/policies/pages/conditions.adoc
internal/conditions/cel.go
internal/conditions/cel_test.go
internal/engine/conf.go
internal/engine/engine.go
internal/engine/engine_test.go
internal/engine/evaluator.go
internal/engine/planner/planner.go
internal/engine/planner/planner_test.go
internal/storage/blob/cloner_test.go
internal/storage/index/builder_test.go
internal/test/testdata/engine/case_18.yaml
internal/test/testdata/query_planner/policies/resource_policy_basics.yaml
internal/test/testdata/query_planner/suite/basics.yaml
internal/test/testdata/store/resource_policies/policy_08.yaml

Closes #1623
This PR introduces a new configuration section, `engine.globals`, which takes a string-to-any map of global variables to be made available in policy conditions as `globals` (aliased to `G`).

feat: Introduce environment-specific global variables

---

cmd/cerbosctl/get/derivedroles/derived_roles.go
cmd/cerbosctl/get/get_test.go
cmd/cerbosctl/get/internal/flagset/filter.go
cmd/cerbosctl/get/internal/policy/policy.go
cmd/cerbosctl/get/principalpolicy/principal_policy.go
cmd/cerbosctl/get/resourcepolicy/resource_policy.go
docs/modules/cli/pages/cerbosctl.adoc
internal/svc/admin_svc.go

Following on from the [newly introduced ListPolicies regex filtering](https://github.com/cerbos/cerbos/pull/1642), used like so:
```sh
cerbosctl --plaintext get rp --name-regexp=foo --scope-regexp=bar --version-regexp=baz
```
closes #1647

enhancement: Add `ListPolicies` filtering ability to `cerbosctl get`

---

docs/modules/configuration/pages/engine.adoc
docs/modules/configuration/partials/fullconfiguration.adoc
docs/modules/policies/pages/scoped_policies.adoc
internal/compile/manager.go
internal/compile/manager_test.go
internal/engine/conf.go
internal/engine/engine.go
internal/engine/engine_test.go
internal/namer/namer.go
internal/namer/namer_test.go
internal/storage/blob/store.go
internal/storage/bundle/bundle.go
internal/storage/bundle/local_source.go
internal/storage/bundle/local_source_test.go
internal/storage/bundle/remote_source.go
internal/storage/bundle/source_wrappers.go
internal/storage/bundle/store.go
internal/storage/db/internal/db.go
internal/storage/db/internal/tests.go
internal/storage/disk/disk.go
internal/storage/git/store.go
internal/storage/index/index.go
internal/storage/index/index_test.go
internal/storage/overlay/store.go
internal/storage/overlay/store_test.go
internal/storage/store.go
internal/test/mocks/Index.go
internal/test/testdata/engine_lenient_scope_search/case_lenient_00.yaml
internal/test/testdata/engine_lenient_scope_search/case_lenient_01.yaml

When configured with `--set=engine.lenientScopeSearch=true`, performs a
search down the scope tree until a policy is found. Originally, if the
request defined scope `a.b.c` a policy file with scope `a.b.c` had to
exist in the store. With this configuration if `a.b.c` doesn't exist,
the engine will try to load `a.b`, `a` and `` in that order.
Fixes #1587

feat: Lenient scope search

---

e2e/lenientscopes/create-policy-secret.sh
e2e/lenientscopes/helmfile.yaml
e2e/lenientscopes/lenientscopes_test.go

Run an E2E suite with lenient scopes enabled to ensure there are no
regressions.

chore(test): Add E2E test for lenient scopes

---

client/model.go

Add methods to return the ID, roles and resource kind of `Principal` and
`Resource` object builders in the SDK. Also adds `Proto` method to
return the underlying protobuf of each of those objects.

enhancement(sdk): Add getters for principal and resource ID fields

---

.github/workflows/pr-test.yaml
.golangci.yaml

Disable caching in the `setup-go` step.
Also removes the Go version config line from .golangci.yaml which would
then force golangci-lint to pick the Go version from `go.mod`.
https://github.com/golangci/golangci-lint/blob/043c368f2d6f5a4f5a46dcd1a14155cbc090ebdd/.golangci.reference.yml#L71-L74

chore(ci): Disable cache of Go installation for GolangCI

---

.github/workflows/vulnerability-check.yaml

`govulncheck` doesn't seem to recognize the `-v` flag.
Related issue: https://github.com/golang/go/issues/61144

chore(e2e): Run govulncheck without verbose flag

---

e2e/overlay/helmfile.yaml

A change to the [underlying postgres image](https://artifacthub.io/packages/helm/bitnami/postgresql) used in our e2e overlay test caused some errors related to duplicate namespaces with the `kubectl create namespace` command - perhaps (and I'm guessing here) due to being unable to teardown the namespace prior to generating it again on the next test. There were a few fixes for bugs appearing around version 12.6.1:
https://github.com/bitnami/charts/commit/262f4f1d2906226cee8cabb49c8fedf97ecc30e4
https://github.com/bitnami/charts/commit/d6234d8b8921470066e567832660164d84192975
Locking to this image version resolves this for now.

fix: Fix overlay e2e test caused by troublesome bitnami postgres image

---

.github/actions/setup-go/action.yaml

When we upgraded to setup-go v4, caching was turned on by default. We don't need it because we manage the cache manually.

chore(ci): Don't use built-in caching in setup-go action

---

internal/server/server.go
internal/svc/helpers.go

fix: request_id is not logged in the "Handled request" log message (cerbos#1690)

fix: Log request_id in the grpc "Handled request" log message

---

docs/modules/configuration/pages/audit.adoc
docs/modules/releases/nav.adoc
docs/modules/releases/pages/v0.29.0.adoc

chore(release): Add 0.29.0 release notes

---

docs/modules/configuration/partials/fullconfiguration.adoc
internal/server/conf.go

Ignore `PlaygroundEnabled` flag while generating configuration docs.

chore(docs): Ignore PlaygroundEnabled configuration flag

---

.goreleaser.yml

Configure GoReleaser to create PRs instead of directly pushing to the
branch.
Also replaces the deprecated `tap` config with `repository`.

chore(ci): Create PRs for Homebrew formula updates

---

deploy/charts/cerbos/templates/service.yaml
deploy/charts/cerbos/values.yaml

For headless services, `clusterIP` should be set to `None`.

enhancement(helm): Add ability to set clusterIP

---

internal/compile/manager.go
internal/compile/manager_test.go
internal/storage/blob/store_test.go
internal/storage/db/internal/db.go
internal/storage/db/internal/tests.go
internal/storage/disk/dirwatch_test.go
internal/storage/git/store.go
internal/storage/git/store_test.go
internal/storage/index/index.go
internal/storage/store.go

- Fixes the problem with `Disable` and `Enable`. (resolves #1710)

fix: Evict policies from cache after disable or enable

---

docs/modules/ROOT/pages/tutorial/03_calling-cerbos.adoc

Fix typo in 03_calling-cerbos.adoc
Signed-off-by: Ryan Buckley <ridiculous@hey.com>

docs(backport): Fix typo in 03_calling-cerbos.adoc (#1714)

---

docs/antora-playbook.yml
docs/modules/policies/pages/derived_roles.adoc
docs/modules/recipes/pages/orm/prisma/index.adoc
docs/modules/recipes/pages/orm/sqlalchemy/index.adoc

Exclude versions before 0.26 as they are quite old and slow down the
build process for not much benefit.
Also fixes some of the warnings from Antora on the `main` branch.

docs: Stop building docs for older versions

---

cmd/cerbos/compile/compile.go

Allow `cerbos compile` to work with policies stored in archive files.

enhancement: Compile and run tests from an archive

---

internal/engine/planner/ast.go
internal/test/testdata/query_planner/policies/resource_policy_leave_request.yaml
internal/test/testdata/query_planner/suite/harry.yaml

fix(planner): Lambda body can be a field selection

---

docs/modules/ROOT/pages/tutorial/03_calling-cerbos.adoc

docs(backport): Typo in Calling Cerbos (#1726)

---

deploy/charts/cerbos/templates/_helpers.tpl
deploy/charts/cerbos/templates/deployment.yaml
deploy/charts/cerbos/values.yaml

This PR adds an `image.digest` value to the Helm chart, to support pinning the image to a digest rather than a tag. This is particularly useful for deploying a specific prerelease version rather than tracking the `dev` tag.

enhancement(helm): Allow an image digest to be provided instead of a tag

---

.github/workflows/snapshot.yaml

At the moment, the only way to pin to a specific prerelease version is to use the image digest, which is difficult to trace back to the source commit.
This PR updates the snapshots workflow to push prerelease images tagged with the commit hash as well as `dev`.

chore(ci): Publish prerelease images tagged by commit hash

---

docs/modules/api/pages/index.adoc

docs(backport): Remove deprecated endpoint/rpc (#1734)

---

docs/modules/policies/pages/conditions.adoc

Updates example conditions and add a tip explaining why

docs: Update examples for handling expressions beginning with quote

---

docs/modules/configuration/pages/storage.adoc
docs/modules/configuration/partials/db_sync.adoc

docs: Caveats of sharing a DB with multiple instances

---

cmd/cerbos/compile/compile.go
docs/modules/policies/pages/compile.adoc

Provide more details in the error messages produced by the `compile`
command.

enhancement: Better error messages from compile command

---

.github/workflows/pr-test.yaml

The `upload-test-times` job is currently being skipped if a `test` job fails, which means the required PR check is ignored.
This PR ensures that the `upload-test-time` job runs if the `test` jobs run, and that it fails if the tests failed.

chore(ci): Always run `upload-test-times` after `test`

---

.github/workflows/e2e.yaml
.github/workflows/snapshot.yaml
e2e/run.sh

Also removes the E2E upload because we need to build a special binary to
capture E2E coverage (#1763).

chore(ci): Upload test coverage from snapshot builds

---

CONTRIBUTING.md
Makefile
go.mod
hack/tools/protoc-gen-jsonschema/go.mod
hack/tools/testsplit/go.mod
internal/storage/git/store.go
internal/util/filesystem.go
tools/go.mod

Go 1.19 is no longer supported now that 1.21 is out. We already use 1.20 in CI, so this PR updates the version in go.mod and CONTRIBUTING.md to match.
I've also replaced a couple of usages of `strings.TrimPrefix` followed by a check if the string was actually trimmed with the [`strings.CutPrefix`](https://pkg.go.dev/strings#CutPrefix) function introduced in Go 1.20.

chore: Update Go to v1.20

---

.github/actions/setup-go/action.yaml
.github/workflows/pr-test.yaml
Makefile

[Go 1.21](https://go.dev/doc/go1.21) released, and introduces a preview of a language change that could find its place in the newer versions: [LoopvarExperiment](https://go.dev/wiki/LoopvarExperiment)
This PR enables this experimental change in the CI. Also, it changes `CERBOS_LOG_LEVEL` to `DEBUG` for the tests.

chore(ci): Use experimental 'loopvar' released with Go 1.21

---

go.mod
go.sum

Since `pterm v0.12.67` introduced `slog` which is only available with `go 1.21`, downgrading to `pterm v0.12.66`.

chore(deps): Downgrade pterm to v0.12.66

---

docs/modules/configuration/pages/auxdata.adoc
docs/modules/configuration/partials/fullconfiguration.adoc
internal/auxdata/auxdata.go
internal/auxdata/conf.go
internal/auxdata/conf_test.go
internal/auxdata/jwt.go
internal/auxdata/jwt_test.go
internal/svc/cerbos_svc.go

Allow users to configure how much skew to tolerate when validating `exp`
and `nbf` claims in JWTs.
Also updates the error message returned by the server when invalid JWTs
are encountered because some users found the old message confusing.
Fixes #1789

enhancement: Configurable time skew for JWT validation

---

client/client_test.go

The GH runners have gotten slower recently and lots of tests fail due to timeouts.

chore(ci): Increase timeout for client tests

---

.github/workflows/snapshot.yaml

Split the job into multiple steps so that they can be restarted
individually on failure.

chore(ci): Split snapshots job

---

cmd/cerbosctl/put/put_test.go
internal/conditions/cerbos_lib.go
internal/engine/evaluator.go
internal/engine/planner/planner.go
internal/storage/blob/cloner_test.go
internal/storage/bundle/remote_source_test.go
internal/storage/index/builder_test.go
internal/test/testdata/bundle/bundle.crbp
internal/test/testdata/bundle/manifest.json
internal/test/testdata/engine/case_20.yaml
internal/test/testdata/query_planner/policies/resource_policy_missing_attr.yaml
internal/test/testdata/query_planner/suite/missing_attr.yaml
internal/test/testdata/store/resource_policies/policy_13.yaml

Ignore expressions that access non-existent keys or try to perform unsupported operations such as `null && true`. 
Fixes #1798

fix: Ignore invalid expressions

---

api/private/buf.lock
api/public/buf.lock

Buf publish is failing because the dependencies are outdated.

chore: Update Buf modules

---

docs/modules/configuration/pages/auxdata.adoc
docs/modules/configuration/partials/fullconfiguration.adoc
internal/auxdata/conf.go
internal/auxdata/jwt.go
internal/auxdata/jwt_test.go
internal/server/server.go

Allow the use of keysets that do not have an `alg` field or a `kid`
field. This is an opt-in feature.

enhancement: Allow parsing JWTs with legacy keysets

---

deploy/charts/cerbos/templates/_helpers.tpl
deploy/charts/cerbos/templates/deployment.yaml
deploy/charts/cerbos/values.yaml

Adds ability to define `topologySpreadConstraints` for the Cerbos deployment. 
Supersedes #1820 
Thanks to @psolarcz for the original PR.

enhancement(helm): Add support for defining topology spread constraints

---

internal/verify/test_fixture.go
internal/verify/test_fixture_test.go
internal/verify/verify.go
private/check/check.go
private/compile/compile.go
private/verify/verify.go
private/verify/verify_test.go

Introduce an additional public API to the engine Check functionality.
Additionally, the `compile.Files` API returns an optional index which can be passed to `verify.Files` to prevent the need to build the index twice.
Lastly, an API is exposed which allows the retrieval of TestFixtures from a path within a given FS implementation.

enhancement: Expose private Check API

---

docs/modules/configuration/partials/fullconfiguration.adoc
internal/server/conf.go
internal/server/server.go

Allow users to configure the maximum concurrent streams per gRPC
connection. The default in the `grpc` package is `Math.MaxUint32`
but that seems rather excessive so the new default set by Cerbos
is 1024. Users can set the configuration value to 0 to get back
the previous behaviour.
See https://deps.dev/advisory/osv/GHSA-m425-mq94-257g

enhancement(security)!: Configure gRPC max concurrent streams

---

internal/util/filesystem.go
internal/util/filesystem_test.go
internal/verify/test_fixture.go
internal/verify/test_fixture_test.go
private/check/check.go

Test fixtures now carry info on the discovered path where the fixture file resides. The initial use case for this is to return the filenames from a new method in the private `TestFixtureGetter` API.

chore: Expose discovered test fixture paths

---

tools/go.mod
tools/go.sum
tools/tools.go
tools/tools.mk

We only use it as a testing tool but its dependencies are being included
in the dependency list of the main module and that includes a
GPL-licensed module.

chore: Remove ghz from tools deps

---

internal/verify/test_fixture.go
internal/verify/verify.go
private/check/check.go

Passing `continueOnError == true` to `LoadTestFixture` will finish attempting to load all principals, resources and auxData. Any errors that occur will be stored on the type for processing later. Passing `false` will maintain current behaviour.

chore: Allow LoadTestFixture to continue on error

---

internal/verify/test_fixture.go
private/check/check.go

Adds an API which traverses the fs.FS and loads the test fixture for any non-nested directory called `testdata`

chore: Add pre-cache API to TestFixtureGetter

---

internal/jsonschema/jsonschema.go
internal/test/testdata/verify/cases/case_016.yaml
internal/test/testdata/verify/cases/case_016.yaml.golden
internal/test/testdata/verify/cases/case_016.yaml.input
internal/test/testdata/verify/cases/case_017.yaml
internal/test/testdata/verify/cases/case_017.yaml.golden
internal/test/testdata/verify/cases/case_017.yaml.input
internal/test/testdata/verify/cases/case_018.yaml
internal/test/testdata/verify/cases/case_018.yaml.golden
internal/test/testdata/verify/cases/case_018.yaml.input

If the fixture files were not named
`testdata/{auxdata,principals,resources}.yaml` Cerbos versions up to
0.31 panicked. That's been inadvertently fixed in `main` but it needs
tests to make sure there are no regressions.

chore: Add tests to check fixture loading from testdata

---

internal/jsonschema/jsonschema.go
internal/storage/index/builder.go
internal/storage/index/builder_test.go
internal/test/testdata/index/corrupt_files.yaml
internal/test/testdata/index/incomplete_files.yaml
internal/test/testdata/index/valid_files.yaml
internal/test/testdata/server/playground/evaluate/pge_invalid_case_01.yaml
internal/test/testdata/server/playground/test/pgt_invalid_case_01.yaml
internal/test/testdata/server/playground/test/pgt_invalid_case_02.yaml
internal/test/testdata/server/playground/validate/pgv_invalid_case_01.yaml
internal/test/testdata/verify/cases/case_004.yaml.golden
internal/test/testdata/verify/cases/case_005.yaml.golden
internal/test/testdata/verify/cases/case_007.yaml.golden
internal/test/testdata/verify/cases/case_014.yaml.golden
internal/util/serdeio.go

- Ignore empty files or files with commented out contents when building the index.
- Use the same YAML library for reading policies and validating them
Fixes #1880
Fixes #1883

fix: Ignore empty files in policy repository

---

internal/engine/planner/planner.go

CEL 0.18.2 [added a method](https://github.com/google/cel-go/issues/789#issuecomment-1804865275) to get the native AST object from the AST wrapper.

chore: Simplify residual expression

---

go.mod
go.sum
internal/server/server.go

The traces don't propagate correctly without it.

chore: Enable Otel interceptor for grpc-gateway client

---

docs/modules/releases/nav.adoc
docs/modules/releases/pages/v0.32.0.adoc

Backport of #1894 because I forgot to merge release notes before the release 🤦🏽

chore(release): Add 0.32.0 release notes (#1894)

---

cmd/cerbosctl/put/put_test.go
internal/policy/policy.go
internal/svc/admin_svc.go

Preserve the timestamp the Admin API was used to update a policy by
saving it as a source attribute.

enhancement: Add Admin API update timestamp to policy

---

.goreleaser.yml
hack/scripts/prep-release.sh

Modules within a monorepo should be tagged with the path to the module
according to https://go.dev/ref/mod#vcs-version. This PR updates the
release script to tag the API module appropriately as Renovate seems to
trip over it.

chore: Tag API module during release

---

deploy/charts/cerbos/templates/deployment.yaml
deploy/charts/cerbos/values.yaml

Allow injecting specific labels into the pod template.
Some tools (e.g. istio), require the addition of labels to deployments. It is better that these are constrained to the pods, rather than added via commonLabels.

enhancement(helm): Add podLabels to the chart

---

tools/go.mod
tools/go.sum

v1.0.0 was retracted.
Required by #1922.

chore(deps): Downgrade github.com/chigopher/pathlib

---

internal/conditions/cel.go
internal/engine/planner/planner.go
internal/engine/planner/planner_test.go
internal/test/testdata/query_planner/policies/derived_roles/org_admin.yaml
internal/test/testdata/query_planner/policies/resource_policy_not-org.yaml
internal/test/testdata/query_planner/policies/resource_policy_org.yaml
internal/test/testdata/query_planner/suite/resource_kind_evaluated.yaml

Resource kind is a known variable and MUST be considered while evaluating expressions:
```yaml
apiVersion: api.cerbos.dev/v1
derivedRoles:
name: org_admin_role
definitions:
- name: org_admin
parentRoles:
- USER_ORG
condition:
match:
any:
of:
- expr: R.kind == "organization" && R.attr.team == "RED"
- expr: request.resource.kind != "organization" && R.attr.team == "BLUE"
```
The PR fixes this.

fix(planner): Query planner must (pre)evaluate expressions with resource kind

---

docs/antora-playbook.yml
docs/modules/ROOT/partials/attributes.adoc
hack/scripts/prep-release.sh
netlify.toml

Remove the older versions of documentation because they just add to
build times. We've managed to maintain backward compatibility quite well
over the releases so referencing the newer docs should still work for
those who are absolutely stuck running very old versions of Cerbos.
Also adds a banner to docs to warn users that they are looking at an old
version.

docs: Remove older versions

---

.github/workflows/vulnerability-check.yaml

It otherwise fails with:
```
govulncheck: loading modules: /opt/hostedtoolcache/go/1.21.6/x64/bin/go list -m -json -mod=mod all: exit status 1
go: -mod may only be set to readonly when in workspace mode, but it is set to "mod"
Remove the -mod flag to use the default readonly value,
or set GOWORK=off to disable workspace mode.
```

chore: Switch workspace mode off for vulnerability check

---

docs/antora-playbook.yml
hack/scripts/prep-release.sh

A typo in the release script made the old branch filter ineffective

docs: Fix branch filter

---

.github/workflows/snapshot.yaml

Cosign requires `id-token: write` permission.

chore(ci): Add correct permissions to snapshot job

---

Makefile
internal/audit/context.go
internal/engine/engine_test.go
internal/server/server.go

The peer address stored in the audit log is the gRPC peer address. When
there's a HTTP request, because it goes through the gRPC gateway, the
peer address reported by gRPC metadata is the localhost address.
This PR updates the gateway configuration to capture the HTTP remote
address and store it in metadata so that the audit log can record the
actual originator of the request.

fix: Record HTTP remote address as peer address for HTTP requests

---

.github/workflows/vulnerability-check.yaml
go.mod

The currently released version seems to have a bug because it
incorrectly complains about missing symbols.

chore(ci): Use master version of govulncheck

---

Dockerfile.cerbos

In Docker Compose, the helathcheck interval can add an artificial delay
because it waits for the first healthcheck to run.

chore: Reduce Docker healthcheck interval

---

Dockerfile.cerbos

Thanks to @haines for pointing out that `start-period` being less than
`interval` doesn't make sense.
Since Cerbos is pretty quick to start up, there's no point in setting
`start-period` at all.

chore: Remove start-period from Docker health check

---

internal/test/testdata/compile/simple_valid_policy_set.yaml.golden
internal/test/testdata/compile/simple_valid_policy_set.yaml.input
internal/test/testdata/compile/yaml_comment_in_condition.yaml
internal/test/testdata/compile/yaml_comment_in_condition.yaml.input
internal/test/testdata/parser/case_001.json
internal/test/testdata/parser/case_001.json.input
internal/test/testdata/store/resource_policies/policy_01.yaml

The old parser stripped out YAML comments from inside literal blocks as
well. That behaviour is incorrect because the spec doesn't allow
comments inside scalars. Comments for CEL expressions should use `//`
for comments instead.

chore: Add test cases for comments inside condition blocks

---

docs/modules/policies/pages/resource_policies.adoc

The leading spaces cause the directive to be rendered literally

docs(backport): Fix leading space in include directive (#1995)

---

.goreleaser.yml
docs/modules/ROOT/pages/installation/container.adoc

Generate a cosign bundle file to help with verifying the binaries.

chore(ci): Generate cosign bundle for binaries

---

.github/workflows/e2e.yaml

E2E tests were failing due to no disk space being available. This PR fixes this by executing the action https://github.com/marketplace/actions/free-disk-space-ubuntu.
Errors
```
setup.go:88:   Warning  Failed     2m8s (x6 over 4m41s)   kubelet            Error: ImagePullBackOff
setup.go:88:   Normal   BackOff    117s (x7 over 4m41s)   kubelet            Back-off pulling image "mcr.microsoft.com/azure-sql-edge:latest"
setup.go:88:   Warning  Failed     2m19s                  kubelet            Failed to pull image “[mcr.microsoft.com/azure-sql-edge:latest](http://mcr.microsoft.com/azure-sql-edge:latest)”: rpc error: code = Unknown desc = failed to pull and unpack image “[mcr.microsoft.com/azure-sql-edge:latest](http://mcr.microsoft.com/azure-sql-edge:latest)”: failed to extract layer …
```

chore(ci): Fix disk space problem on E2E tests

---

cmd/cerbos/main.go
cmd/cerbosctl/main.go
cmd/cerbosctl/root/root.go
cmd/cerbosctl/version/version.go
docs/modules/cli/pages/cerbos.adoc
docs/modules/cli/pages/cerbosctl.adoc

This PR adds a `--client` flag to `cerbosctl version`, so that it is possible to check the version of `cerbosctl` without specifying credentials or attempting to connect to a PDP server.
It also adds missing help text to the `cerbos --version` flag, and fixes the top-level help of `cerbosctl` to include the information about providing credentials.

feat: Add `--client` flag to `cerbosctl version`

---

docs/modules/policies/pages/compile.adoc

```
WARN (asciidoctor): no callout found for <18>
file: /github/workspace/cerbos/docs/modules/policies/pages/compile.adoc:121
```

docs: Fix broken callout

---

docs/antora-playbook.yml
hack/scripts/prep-release.sh
netlify.toml

Because Antora doesn't have support for Git LFS, we need to create
redirect rules to load the images correctly. This has to be done on a
version-by-version basis to avoid redirect loops.

chore(docs): Add redirects for image URLs

---

go.mod
go.sum
internal/storage/bundle/remote_source.go
internal/storage/bundle/remote_source_test.go

Some config fields have moved in the latest version.

chore: Update cloud-api usage

---

hack/tools/generate-npm-packages/templates/wrapper/package.json
npm/packages/cerbos/package.json
npm/packages/cerbosctl/package.json

This PR adds keywords to the `cerbos` and `cerbosctl` npm packages to improve discoverability on npmjs.com.
Related PR for the JS SDK: https://github.com/cerbos/cerbos-sdk-javascript/pull/859

chore: Add keywords to npm packages

---

docs/modules/configuration/partials/fullconfiguration.adoc
hack/dev/conf.secure.bundle.yaml
internal/hub/conf.go
internal/server/server_test.go
internal/storage/bundle/conf.go
internal/storage/bundle/conf_test.go
internal/storage/bundle/local_source.go
internal/storage/bundle/remote_source.go
internal/storage/bundle/remote_source_test.go
internal/util/app.go

Move credentials and connection settings to their own configuration section under `hub` so that they can be shared.

chore: Refactor Cerbos Hub configuration

---

internal/engine/planner/internal/utils.go
internal/engine/planner/matchers/struct_matcher.go
internal/engine/planner/matchers/struct_matcher_test.go
internal/test/testdata/query_planner/policies/resource_policy_report_with_map.yaml
internal/test/testdata/query_planner/suite/report_with_map.yaml

fix(plan): P.attr.workspaces[R.id].role == "OWNER" must be simplified

---

Makefile
docs/modules/configuration/partials/fullconfiguration.adoc
go.sum
hack/tools/confdocs/confdocs.go
internal/audit/cerboshub/cerboshub.go
internal/audit/cerboshub/cerboshub_test.go
internal/audit/cerboshub/conf.go
internal/audit/cerboshub/ingest.go
internal/audit/hub/conf.go
internal/audit/hub/hub.go
internal/audit/hub/hub_test.go
internal/audit/hub/ingest.go
internal/audit/local/badgerdb.go
internal/audit/local/badgerdb_test.go
internal/server/server.go
internal/test/mocks/IngestSyncer.go
internal/util/app.go

This PR wires up the `IngestSyncer` with the new Cloud API client.
* I've separated the key scan into two concurrent streams (access + decision logs) to avoid fiddly logic to infer types from each key when retrieving the access log (retrieving the log requires reading sync keys, retrieving the actual log key, then retrieving the log value with that key).
* I've also reworked the `ForceWrite` logic in an attempt to fix the flakey tests 🤞.
* I've temporarily reverted the commit which renames `cerboshub` -> `hub` as it ruined the PR diff, I can add this back in afterwards.

feat: Integrate `hub` audit backend with cloud api

---

.github/workflows/release.yaml
.github/workflows/snapshot.yaml

The cosign step is failing because of a failure to read remote keys.
This seems to be a problem that crops up from time-to-time with new
releases of cosign. Unpinning the version and installing the latest
available one should help fix it.

chore(ci): Unpin cosign version

---

.github/workflows/e2e.yaml
e2e/kind.yaml
e2e/overlay/helmfile.yaml
e2e/postgres/helmfile.yaml
internal/test/e2e/setup.go

The new version of the Postgres Helm chart does not mount the data volume by default and causes the container to fail. This PR fixes the mount and also adds extra debug statements that would be useful in the future to investigate similar failures.

chore(ci): Fix Postgres data volume for E2E tests

---

docs/modules/ROOT/examples/quickstart/example.cs

Specifying a policy version for the resource "DAFFY002" in the .NET SDK version of the quickstart docs causes the final step to not work as described.
Removing this policy version specification fixes the issue, and the quickstart works as intended.
Fixes #2064

docs: Remove policy version from .NET quickstart

---

docs/modules/ROOT/examples/quickstart/example.cs

docs(backport): Remove policy version from .NET quickstart (#2065)

---

docs/supplemental-ui/css/site-extra.css

resolves #2067
Before
---
After ([c68ef76](https://github.com/cerbos/cerbos/pull/2069/commits/c68ef769eabf291aaad7e80f40fe4aa058fc1958))
---

chore(docs): Improve documentation accessibility

---

internal/compile/manager.go
internal/compile/manager_test.go
internal/test/policy.go

When lenient scope search is enabled and we have a set of candidates to
search for, we incorrectly search the cache for all of those and return
the first one found. If we don't find the first candidate in the cache,
we should just hit the store because it could have been added to the
repo since we last looked for it.
Fixes #1846

fix: Skip compile cache if first candidate doesn't exist

---

internal/storage/bundle/bundle.go
internal/storage/bundle/local_source_test.go
internal/storage/db/internal/db.go
internal/storage/db/internal/tests.go
internal/storage/index/index.go

`cerbos.resource.leave_request.vdefault/regional` to `resource.leave_request.vdefault/regional`

chore: InspectPolicies returns FQN instead of policy key

---

.github/renovate.json

The Renovate `config:base` preset includes the [`:ignoreModulesAndTests`](https://docs.renovatebot.com/presets-default/#ignoremodulesandtests) preset, which means that it's ignoring packages under `npm/test`.
This PR
- removes the `config:base` preset (which has been replaced by [`config:recommended`](https://docs.renovatebot.com/presets-config/#configrecommended) anyway) and inlines the only preset included in it that we actually need ([`:dependencyDashboard`](https://docs.renovatebot.com/presets-default/#dependencydashboard));
- enables the [`configMigration`](https://docs.renovatebot.com/configuration-options/#configmigration) setting so that we get PRs to keep the file up-to-date; and
- adds `packageRules` to configure the Node.js/npm updates.

chore: Allow Renovate to update npm tests

---

.goreleaser.yml

https://goreleaser.com/deprecations/#brewsfolder

chore: Update deprecated `brews.folder` setting in GoReleaser config

---

.github/workflows/release.yaml
.goreleaser.yml

GoReleaser is hard-coded to look for a `.sig` file for each artifact.

chore(ci): Output signature from cosign

---

.github/actions/publish-docs/action.yaml
.github/workflows/docs.yaml
.github/workflows/release.yaml

The [Netlify CLI action](https://github.com/netlify/actions) is unmaintained and using an EOL Node.js version (which it complains about on install) as well as the deprecated `set-output` syntax. This PR removes the action in favour of installing the CLI ourselves.

chore(ci): Remove unmaintained Netlify action

---

e2e/otlp/helmfile.yaml

The chart's been changed recently to support both Badger and memory as
storage types for the all-in-one deployment.

chore(ci): Update storage type for Jaeger chart

---

.github/workflows/pr-test.yaml

This PR adds a job to the CI workflow to allow us to add the npm package tests as a required check in the branch protection rules, because it's not possible to do so with a matrix job.

chore(ci): Check results of npm package tests

---

cmd/cerbos/healthcheck/healthcheck.go
internal/server/server.go
internal/server/tests.go
internal/util/network.go

The Go gRPC library has changed its behaviour to lazily establish a
connection when the first request is sent. This makes the first request
to Cerbos quite slow to return a response.
Before:
```
DNS Lookup   TCP Connection   Server Processing   Content Transfer
[     0ms    |       0ms      |      20023ms      |        0ms       ]
|                |                   |                  |
namelookup:0ms            |                   |                  |
connect:0ms               |                  |
starttransfer:20038ms          |
total:20038ms
```
After:
```
DNS Lookup   TCP Connection   Server Processing   Content Transfer
[     0ms    |       0ms      |        1ms        |        0ms       ]
|                |                   |                  |
namelookup:0ms            | …
```

fix: Eagerly establish gRPC connection to avoid initial delay

---

go.mod
go.sum
internal/audit/kafka/kafka_test.go
internal/audit/log.go

If requests are very large, serializing them to stdout or files can take
a while. This PR makes the audit log write asynchronous so that the
response can be returned without waiting for slow output sinks.
Write audit log entries asynchronously

enhancement: Write audit logs asynchronously

---

docs/modules/deployment/pages/cloud-platforms.adoc

Topic: Fly listens only on "0.0.0.0"
Changes: Tip added
> Services to be routed to using Fly Proxy need to bind to IPv4 addresses, and services to be reached over 6PN need to bind to IPv6, as described above. However, you may find that your service works even if you haven’t used the addresses we specified. IPv4-mapped IPv6 addresses, if enabled on the VM, can allow IPv4 (and thus Fly Proxy) connections to a service bound on [::]. Further, the wildcard syntax [::] or 0.0.0.0 sometimes covers both IPv4 and IPv6, depending on the language, library, or application.
Fixes #

chore(docs): Update cloud-platforms.adoc

---

internal/audit/log.go

As of https://github.com/cerbos/cerbos/pull/2104, audit log entries may be written after the request completes and the context is cancelled.

fix: Ignore context cancellation when writing audit log entries

---

internal/test/testdata/verify/cases/case_019.yaml.golden
internal/test/testdata/verify/cases/case_019.yaml.input
internal/verify/test_fixture.go

https://github.com/cerbos/cerbos/pull/2116 defaulted the expectation to `EFFECT_DENY`, but didn't include the correct expected value in the failure details 🤦‍♂️

fix: Include implicit `EFFECT_DENY` in test failure details

---

internal/audit/kafka/tls.go
internal/audit/kafka/tls_test.go

Fixes the follow: 
- allow not setting path to CA to fallback to system
- when supplying own CA, append to system CA

fix: Kafka TLS using system CA

---

internal/audit/kafka/publisher.go
internal/audit/kafka/publisher_test.go

`TryProduce` is similar to the previous `Produce` call, but rather than blocking if the Kafka client currently has MaxBufferedRecords or MaxBufferedBytes buffered, this fails immediately.
https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#Client.TryProduce
Cerbos when configured with `produceSync: false` should handle an outage at the Kafka layer by continuing but reporting the problem through metrics & logs.
Fixes #2123

fix: Stop blocking Kafka audit publishing when an outage occurs

---

internal/parser/parser.go
private/compile/compile.go

There are some edge cases where the parser can panic but we don't have
any code samples that trigger it. This PR handles panics and attaches
the context to the error to help us debug those cases.

chore: Handle panics during parsing

---

internal/storage/db/mysql/schema.sql

The `mysql_native_password` plugin is deprecated and not available on
latest MySQL container images.

chore: Remove usage of deprecated MySQL native authentication plugin

---

cmd/cerbosctl/internal/client/client.go
go.mod
go.sum
internal/parser/parser_test.go

Update our fork with the performance patch from https://github.com/goccy/go-yaml/pull/438.
```
goos: linux
goarch: amd64
pkg: github.com/cerbos/cerbos/internal/parser
cpu: 13th Gen Intel(R) Core(TM) i7-1360P
│ parser_before.txt │          parser_after.txt           │
│      sec/op       │   sec/op     vs base                │
Unmarshal/10-16         3399.0µ ± 3%   847.2µ ± 4%  -75.08% (p=0.000 n=10)
Unmarshal/50-16         50.093m ± 7%   3.847m ± 2%  -92.32% (p=0.000 n=10)
Unmarshal/100-16       191.559m ± 6%   7.504m ± 3%  -96.08% (p=0.000 n=10)
Unmarshal/500-16       4674.56m ± 3%   35.09m ± 4%  -99.25% (p=0.000 n=10)
geomean                  111.1m        5.412m       -95.13%
│ parser_before.txt │             parser_after.txt              │
│        B/s        │      B/s        vs base …
```

enhancement: Apply perf patch to YAML parser

---

cmd/cerbos/server/server.go

chore: Use new hub configuration for env var override

---

.github/workflows/release.yaml

The worker is running out of disk space during the release.

chore(ci): Clear disk space for release workflow

---

.github/renovate.json
.github/workflows/pr-test.yaml
.github/workflows/release.yaml

Also includes a tweak to Renovate to ignore the go-yaml replacement and
update import paths on major module version updates.

chore(ci): Clear disk space for npm build

---

go.mod
go.sum
internal/parser/parser.go
internal/test/testdata/parser/case_023.json
internal/test/testdata/parser/case_023.json.input

The upstream YAML parser doesn't expose syntax errors in a way that we
could easily obtain information about the context. I've updated our fork
to make this easier and enable us to report syntax errors in the same
way as other errors.

enhancement: Context for YAML syntax errors

---

internal/audit/context.go
internal/server/headers_test.go
internal/server/server.go

This PR primarily aims to work around an issue with `X-Forwarded-For` handling in the gRPC-Gateway (https://github.com/grpc-ecosystem/grpc-gateway/issues/4320).
Given a remote IP of 4.4.4.4 sending incoming headers of 
```
X-Forwarded-For: 1.1.1.1, 2.2.2.2
X-Forwarded-For: 3.3.3.3
```
the resulting headers forwarded by the gRPC-gateway are
```
X-Forwarded-For: 1.1.1.1, 2.2.2.2
X-Forwarded-For: 3.3.3.3
X-Forwarded-For: 1.1.1.1, 2.2.2.2, 4.4.4.4
```
The workaround I have added means that the resulting headers are
```
X-Forwarded-For: 1.1.1.1, 2.2.2.2
X-Forwarded-For: 3.3.3.3
X-Forwarded-For: 4.4.4.4
```
We now join the values with `", "` rather than `"|"` to preserve the [de-facto standard syntax](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#syntax).
This PR …

fix: Work around gRPC-Gateway bug in `X-Forwarded-For` handling

---

go.mod
go.sum
internal/parser/parser_test.go
internal/test/testdata/parser/case_024.json
internal/test/testdata/parser/case_024.json.input

The bug was patched in the parser (cerbos/go-yaml#3). This PR adds a
test for it.
Fixes #2146

fix: Detect incorrectly indented YAML

---

netlify.toml

Netlify documentation is not clear about how to handle 404 errors and I
wrongly assumed it needed to have the status code parameter set to 404.
It actually sends a 404 back to the user :man_facepalming:

chore(docs): Redirect old versions with correct status code

---

deploy/charts/cerbos/templates/deployment.yaml
deploy/charts/cerbos/templates/hpa.yaml
deploy/charts/cerbos/templates/service.yaml
deploy/charts/cerbos/values.yaml
docs/modules/deployment/assets/images/daemonset_deployment.png
docs/modules/deployment/pages/index.adoc
docs/modules/deployment/pages/k8s-daemonset.adoc

This adds support to the chart for deploying as a DaemonSet, and adds additional options
that are common in that scenario. The new settings are
- `type`: defaults to deployment, but can be set to daemonset
- `priorityClassName`: allows setting the pod priorityClassName
- `service.internalTrafficPolicy`: allows forcing traffic to this service to the local pod instance.
TODO:
- Not tested at all
- should add schema validation of the fields
Fixes cerbos/cerbos#1640

enhancement(helm): Allow deploying as a DaemonSet

---

.github/workflows/snapshot.yaml

ECR is immutable and doesn't allow overwriting the `dev` tag.

chore(ci): Skip publishing snapshots to ECR

---

go.mod
go.sum
internal/audit/hub/conf.go
internal/audit/hub/hub.go
internal/audit/hub/hub_test.go
internal/audit/hub/ingest.go
internal/hub/hub.go
internal/storage/hub/conf.go
internal/storage/hub/conf_test.go
internal/storage/hub/remote_source.go
internal/storage/hub/remote_source_test.go
internal/test/mocks/CloudAPIClient.go

Use a singleton Hub base client to share the authentication token
between different APIs.
Requires cerbos/cloud-api#186

chore: Share Hub base client

---

private/check/check.go
private/plan/plan.go

For use in the Hub playground.

chore: Expose `plan.Resources` from `private` package

---

internal/auxdata/jwt.go

I marked this as a chore rather than a fix because it should never happen since JSON objects are string-keyed, but anyway, it seemed like it should be there.

chore: Add missing `continue` to ignore non-string keys in JWT claims

---

internal/audit/hub/hub.go

We observe high memory usage in Cerbos instances which have a `hub` audit backend configured. This is an attempt to reduce memory usage by lazily evaluating buffers produced by the DB scan, and by reusing types which we use as unmarshal targets.

fix: Reduce memory usage in badger stream for hub audit backend

---

go.mod
go.sum
internal/audit/hub/hub.go
internal/audit/hub/hub_test.go
internal/audit/hub/ingest.go
internal/audit/local/badgerdb.go

The callback is in the write path and blocks until the Hub log is done
with its work using its internal timer. By removing this dependency, we
can let the two logs work independently. Even if the Hub sync falls
behind and adds delays to the internal timer, the local log saving
thread can continue to work without being blocked.
The down side of this change is that tests are a bit more flaky.

chore: Remove callback from local audit log

---

cmd/cerbosctl/get/get_test.go
cmd/cerbosctl/get/internal/policy/policy.go
cmd/cerbosctl/get/internal/policy/print.go
cmd/cerbosctl/put/put_test.go
internal/storage/index/stats.go

This branch was originally merged without the standard CI requirements enforced, hence these slipped through the net.
I'll follow up with `Get` and `Put` support in a later item, but want to get it passing predictably for now.

chore: Fix CI checks

---

.goreleaser.yml

Can't push dev and latest tags because the registry is immutable.

chore(ci): Remove AWS dev and latest container tags

---

docs/modules/policies/nav.adoc
docs/modules/policies/pages/index.adoc
docs/modules/policies/pages/role_policies.adoc

Repeating because https://github.com/cerbos/cerbos/pull/2253 was targeting a now-defunct feature branch 🤦‍♂️ -- sorry Charith!
I just cherry-picked the squashed commit from that branch so the diff is identical.

docs: Add role policies sections (#2253)

---

.github/workflows/pr-test.yaml

Seems like GitHub has shrunk the disks on runners recently
🤷🏽‍♂️ 

chore(ci): Clear disk space for upload workflow

---

docs/modules/configuration/pages/audit.adoc

`s/DataDog/Datadog/;`
Source: I worked there for five years and had to correct this _constantly_, even by our own employees.

docs: Spell Datadog properly

---

deploy/charts/cerbos/templates/_helpers.tpl
internal/storage/db/sqlserver/sqlserver_test.go

We currently ignore `cerbos.config.server.httpListenAddr` and
`cerbos.config.server.grpcListenAddr` values and override them
with `cerbos.httpPort` and `cerbos.grpcPort` values. This is problematic
if the users want to set the listen address to a particular IP range.

fix(helm): Allow overriding listen addresses

---

cmd/cerbos/server/server.go
pkg/cerbos/serve.go
pkg/cerbos/serve_test.go

This PR extracts the `cerbos server` command internals to a public `cerbos.Serve` function that runs the PDP server in the current process.

feat: Add public API for running a PDP in-process

---

e2e/sqlserver/chart/values.yaml
e2e/sqlserver/helmfile.yaml

SQL Server container images don't have versioned labels and previously
cached images have an expired certificate that causes the E2E tests to
fail. This PR sets the image pull policy to make sure that the most
up-to-date image is used for tests.

chore(ci): Set SQL Server image pull policy for E2E tests

---

deploy/charts/cerbos/values.schema.json
deploy/charts/cerbos/values.yaml

Helm refuses to work because the schema definition for `initContainers`
doesn't allow items that are objects.

fix(helm): Fix schema definition of initContainers

---

cmd/cerbosctl/inspect/internal/print.go

Displaying attributes in the existing command `cerbosctl inspect policies` seems to work visually.
```
$ cerbosctl inspect policies
POLICY ID : derived_roles/common_roles.yaml
ACTIONS   : 
ATTRIBUTES: R.attr.flagged,R.attr.owner
VARIABLES : 
-------------------
POLICY ID : resource_policies/policy_05_acme.hr.uk.yaml
ACTIONS   : defer,delete
ATTRIBUTES: R.attr.geography
VARIABLES : principal_location
-------------------
```
```
$ cerbosctl inspect policies --no-headers
derived_roles/common_roles.yaml
R.attr.flagged,R.attr.owner
-------------------
resource_policies/policy_05_acme.hr.uk.yaml
defer,delete                                                
R.attr.geography                                                      
principal_location  
-------------------
```

enhancement: Display attributes in the cerbosctl inspect policies command

---

e2e/sqlserver/helmfile.yaml
e2e/sqlserver/sqlserver_test.go
internal/storage/db/sqlserver/sqlserver_test.go

The SQL Server TLS issue still springs up during E2E tests. This is
another attempt to work around it.

chore(ci): Trust SQL Server certificate

---

.justfile
docs/modules/configuration/partials/fullconfiguration.adoc
go.mod
go.sum
hack/tools/confdocs/confdocs.go
hack/tools/confdocs/structtag/LICENSE
hack/tools/confdocs/structtag/tags.go
internal/audit/kafka/conf.go

Parsing logic from `structtag` doesn't have a way to configure whether we want to ignore a `,` character inside of square brackets while splitting the tag value such as;
```
Compression []string `conf:",example=['zstd', 'snappy', 'none']"`
```
This makes us unable to parse array examples such as: `['zstd', 'snappy', 'none']`
One possible solution to this was copying the implementation (or maybe we should fork it?) from `structtag` and modifying it to use [go-andiamo/splitter](github.com/go-andiamo/splitter), which I did for this PR.
fixes #1638

chore(tooling): Fix confdocs not being able to parse examples consisting of an array

---

docs/modules/configuration/pages/storage.adoc

docs(backport): Update sqlite3 example to use proper in-memory DSN (#2317)

---

deploy/charts/cerbos/templates/deployment.yaml

This PR removes the whitespace [chomping](https://helm.sh/docs/chart_template_guide/control_structures/#controlling-whitespace) (`{{- `)  on the `priorityClassName` value to allow the chart to render valid YAML when the `priorityClassName` value is set.
Fixes https://github.com/cerbos/cerbos/issues/2336

fix(helm): Remove whitespace chomp for priorityClassName so valid yaml is rendered

---

docs/modules/configuration/pages/server.adoc
internal/server/middleware.go

Most browsers send the `user-agent` header with CORS requests. The
default set of allowed headers baked into the library doesn't contain
that header.

enhancement: Add user-agent to default allowed headers for CORS

---

hack/scripts/prep-release.sh

Because we have a `go.work` file, the version of `api/genpb` submodule
in `go.mod` is ignored in workspace-aware builds. This is generally what
we want because it makes it much easier to test changes to the
protobufs. However, when we tag a release, we should make sure that the
`go.mod` points to the actual version of the submodule used. This is
important for reproducible builds because Go workspaces are considered a
development aid by some tools and they disable workspace mode when
building from source.
I am currently having trouble building Cerbos 0.39 with Nix because the
tagged version uses v0.38.1 of `api/genpb` which doesn't contain some of
the protobuf definitions used in 0.39.

chore(release): Update generated API module version before tagging

---

cmd/cerbos/repl/internal/repl.go
cmd/cerbosctl/put/put_test.go
internal/conditions/cerbos_lib.go
internal/conditions/cerbos_lib_test.go
internal/engine/engine.go
internal/engine/engine_test.go
internal/engine/evaluator.go
internal/storage/index/builder_test.go
internal/test/testdata/store/resource_policies/policy_15.yaml
private/verify/verify.go

At the moment, `now` is deterministic within a CEL expression. However, within a single check, it varies between conditions of different rules in a policy.
This PR fixes the value of `now` at the time the check (or plan) is initiated instead of the time each expression is evaluated, so that the results are guaranteed to be consistent even between separate evaluations.

enhancement: Make `now` fully deterministic

---

cmd/cerbos/run/run.go

Due to a breaking change in the flag parsing library, the command to
execute was getting prefixed by `--`, which led to `cerbos run` failing 
to work.
This affects Cerbos 0.39. The workaround, until Cerbos 0.40 is released, is
to remove the leading `--` before the command to execute.

fix: Command execution fails with `cerbos run` since v0.39 

---

internal/schema/error.go
internal/test/testdata/schema/fs/_schemas/complex_object.json
internal/test/testdata/schema/test_cases/check_input_01.yaml
internal/test/testdata/schema/test_cases/check_input_03.yaml
internal/test/testdata/schema/test_cases/check_input_07.yaml
internal/test/testdata/schema/test_cases/check_input_08.yaml
internal/test/testdata/schema/test_cases/plan_resources_input_01.yaml
internal/test/testdata/schema/test_cases/plan_resources_input_02.yaml

The validation library doesn't populate the path field for top-level
required fields that are missing. This PR handles that case.
Fixes #2362

fix: Populate path field of validation errors

---

internal/engine/engine.go
internal/engine/planner/planner.go
internal/test/testdata/query_planner/policies/resource_policies/basics.yaml
internal/test/testdata/query_planner/policies/resource_policies/leave_request.yaml
internal/test/testdata/query_planner/policies/resource_policies/top.yaml
internal/test/testdata/query_planner/suite/basics.yaml
internal/test/testdata/query_planner/suite/maggie.yaml
internal/test/testdata/query_planner/suite/wrong_attr_data_type.yaml

When the policy does not have an 'ALLOW' rule and has an unconditional 'DENY' rule, the query planner correctly returns an `ALWAYS_DENIED` response.
```yaml
apiVersion: "api.cerbos.dev/v1"
resourcePolicy:
version: default
resource: x
rules:
- actions:
- write
roles:
- USER
effect: EFFECT_DENY
```
When the policy does not have an 'ALLOW' rule and has a conditional 'DENY' rule:
```yaml
apiVersion: "api.cerbos.dev/v1"
resourcePolicy:
version: default
resource: x
rules:
- actions:
- write
roles:
- USER
effect: EFFECT_DENY
condition:
match:
expr: R.attr.environment == "production"
```
The query planner should also return `ALWAYS_DENIED` response, but instead returns: `AST: (not (eq request.resource.attr.environment "production"))`

fix(plan): A policy with only conditional DENY rule must produce `ALWAYS_DENIED`

---

.goreleaser.yml

https://goreleaser.com/deprecations/#snapshotname_template

chore: Replace deprecated `snapshot.name_template` field in GoReleaser config

---

docs/modules/api/pages/index.adoc

Fixes broken links from #2384 and updates the copy to point out new BSR features.

docs: Update gRPC API section

---

internal/inspect/inspect_test.go
internal/inspect/policyset.go
internal/inspect/visit.go
internal/test/testdata/inspect/outputs.yaml

Currently we don't inspect policy output expressions, so attributes might not be listed and constants/variables are incorrectly marked as unused.
This PR fixes that.

fix: Inspect policy output expressions

---

go.mod
go.sum
hack/tools/testsplit/go.mod
hack/tools/testsplit/go.sum

The issue alecthomas/kong#475 is fixed with the `v1.5.1`. ([fixing commit](https://github.com/alecthomas/kong/commit/81d0c29303442ba216395c690b07526ede3ca34a#diff-d789b1adb70876292f4e6e6b8a2cc6a4b6731375f81a717587e97fa9301f1c26R305))
Resolves cerbos/cerbos#2402.

chore(deps): Update alecthomas/kong to v1.5.1

---

cmd/cerbosctl/put/put_test.go
internal/storage/index/builder_test.go
internal/test/testdata/store/resource_policies/policy_16.yaml
internal/test/testdata/verify/cases/case_037.yaml
internal/test/testdata/verify/cases/case_037.yaml.golden
internal/test/testdata/verify/cases/case_037.yaml.input
internal/verify/test_matrix.go

If a test defines an output expectation for an action that doesn't exist
in the input actions list, fail the test.

enhancement: Fail tests with unreachable output expectations

---

docs/modules/ROOT/pages/tutorial/03_calling-cerbos.adoc

This PR fixes the tutorial's [third page](https://docs.cerbos.dev/cerbos/latest/tutorial/03_calling-cerbos) to replaces the deprecated `/api/check` endpoint usage with `/api/check/resources` endpoint.
- Updated the request format
- Updated the response
- Updated the cURL command

docs: Update 03_calling-cerbos.adoc of tutorial to use the updated `/api/check/resources` endpoint

---

docs/modules/ROOT/pages/tutorial/03_calling-cerbos.adoc

This PR fixes the tutorial's [third
page](https://docs.cerbos.dev/cerbos/latest/tutorial/03_calling-cerbos) to replaces the deprecated `/api/check` endpoint usage with `/api/check/resources` endpoint.
- Updated the request format
- Updated the response
- Updated the cURL command
Fixes #

docs(backport): Update 03_calling-cerbos.adoc of tutorial 

---

internal/engine/engine.go
internal/engine/engine_test.go
internal/engine/evaluator.go
internal/engine/ruletable/rule_table.go
internal/server/server.go

Expressions are now checked and compiled to CEL programs at build time rather than at evaluation time, thus reducing hot-path CPU pressure.
This is now more performant than the original, pre ruletable engine (for relevant engine test cases 0-23):
- `sec/op`: -15%
- `allocs/op`: -16%
- `b/ops`: -18%
And the current rule table implementation:
- `sec/op`: -24%
- `allocs/op`: -20%
- `b/ops`: -22%

enhancement: Pre-compile rule table CEL programs

---

internal/engine/ruletable/rule_table.go
internal/util/globs.go

We don't want to match glob patterns when building the rule table index as this leads to non-deterministic outputs and confused developers. Glob matching is only required at eval time.
The feature branch will be good to go after this!

fix: Correctly handle GlobMap creation

---

docs/modules/policies/pages/conditions.adoc

Update docs to correct some errors in the CEL math function examples.

docs: Correct examples for math functions

---

internal/engine/engine.go
internal/engine/planner/planner.go

These issues were picked up in the JS SDK tests: https://github.com/cerbos/cerbos-sdk-javascript/actions/runs/12745231739
I've been able to partially verify locally with manual requests against a PDP and JS SDK tests but am struggling to do so like for like with the CI environment (I'm seeing other unrelated failures etc). The fixes seem simple enough so it's probably more time efficient to merge these and see if they resolve errors in the SDK.
I need to add query planner tests, but I'll do that in a separate follow-up item as it seems fairly involved and I'm away for the latter part of this week--I'm keen to get these fixes in ASAP.

fix: Return validation errors and effective policies in query planner responses

---

internal/server/server_test.go
internal/test/testdata/server/plan_resources/plan_case_03.yaml

Should solve [this e2e test failure](https://github.com/cerbos/cerbos/actions/runs/12759334544/job/35562917228).
Looks like there's a minor discrepancy between precompiled rule tables and dynamically generated ones--I'll investigate in another issue.

fix: Use correct filterDebug type in e2e query planner test

---

internal/engine/engine.go
internal/engine/evaluator.go
internal/engine/planner/planner.go
internal/test/testdata/verify/cases/case_033.yaml.golden
internal/test/testdata/verify/cases/case_034.yaml.golden

Rather embarrassingly, there were previously working tests covering this case but I erroneously changed them as part of the original [rule table PR](https://github.com/cerbos/cerbos/pull/2442/files):
This PR fixes the issue whereby engine settings were ignored, and correctly reinstates the valid test expectations.

fix: Correctly handle defaultPolicyVersion engine config

---

internal/engine/engine.go
internal/engine/planner/planner.go

Follow-up from #2449 to apply the default policy version fallback sooner so that it also is used for the `engine.getPartialRuleTable` lookup.

fix: Fall back to default policy version sooner in query planner

---

cmd/cerbos/compile/compile.go
hack/tools/confdocs/confdocs.go
internal/engine/engine.go
internal/svc/playground_svc.go
private/check/check.go
private/engine/engine.go
private/plan/plan.go
private/verify/verify.go

This PR changes the `engine.NewEphemeral` function to accept an `*engine.Conf` parameter, so that a non-default configuration can be applied in the Hub playground.

chore: Make ephemeral engine configurable

---

internal/server/server.go

Previously, the code determining whether or not to generate a partial rule table was incorrect, as the rule table could never be nil (so it would always look for the precompiled table).
We don't subscribe the rule table to change events unless we're precompiling the full rule table at start time, as the evaluator builds a partial rule table from underlying store state at evaluation time.
This seems to fix the broken tests for the JS and Go SDKs when run locally. I'm having some trouble with the E2E test suite so have been unable to confirm those.
This'll hopefully fix the broken Admin API tests for now. In general, I think maintaining partial rule table generation is confusing--I'll look at unifying (all stores using a full rule table) in a follow up item.

fix: Correctly handle partial rule table and event subscription

---

cmd/cerbos/run/run.go
go.mod
go.sum
pkg/cerbos/serve.go

Apparently, the cgroups are not correctly set on ECS and the CFS quota
cannot be determined by automaxprocs. See uber-go/automaxprocs#66.

enhancement: Correctly set GOMAXPROCS on ECS

---

cmd/cerbosctl/put/put_test.go
internal/compile/manager.go
internal/engine/engine.go
internal/engine/engine_test.go
internal/engine/evaluator.go
internal/engine/planner/planner.go
internal/engine/ruletable/rule_table.go
internal/engine/ruletable/rule_table_test.go
internal/namer/namer.go
internal/server/server.go
internal/server/server_test.go
internal/storage/index/builder_test.go
internal/test/testdata/engine/case_26.yaml
internal/test/testdata/server/plan_resources/plan_case_03.yaml
internal/test/testdata/server/plan_resources/plan_case_04.yaml
internal/test/testdata/server/playground/proxy/pgp_rqp_case_05.yaml
internal/test/testdata/store/principal_policies/policy_02_acme.yaml
internal/test/testdata/store/resource_policies/policy_17.yaml
internal/util/globs.go
internal/verify/junit/junit_test.go
internal/verify/verify_test.go

Introduce a single rule table implementation which is empty on start and lazily loads required policies as they're queried. Enables this rule table for all store types.
Also solves some other issues:
* Makes query planner empty-case output consistent
* Fixes E2E tests
* Fixes principal policy `scopePermissions: *REQUIRES_PARENTAL_CONSENT` fall through behaviour

enhancement: Lazy rule table

---

internal/engine/ruletable/rule_table.go

After a store reload, the rule table should only purge caches rather than attempting to reload all policies, as this is now handled via lazy loads at query time.
This fixes the [failures in the JS SDK tests](https://github.com/cerbos/cerbos-sdk-javascript/actions/runs/13104568319/attempts/1).

fix: Rule table reload should only purge

---

cmd/cerbos/healthcheck/healthcheck.go
cmd/cerbos/healthcheck/healthcheck_test.go

I noticed that the `cerbos healthcheck` command specifies `cerbos.svc.v1.CerbosService` when checking health via gRPC but not via HTTP. I'm not sure it really matters, but this PR makes it consistent.

chore: Specify service when checking health via HTTP

---

.github/workflows/pr-test.yaml
.github/workflows/snapshot.yaml

At time of writing, an [outage at Coveralls](https://status.coveralls.io/incidents/0nz347snpb16) has been ongoing for 19 hours. This impacts our `pr-test` and `snapshop` workflows. Disabling will enable us to continue to merge PRs--we can reenable once the incident is resolved.
We'll (ironically) need to bypass PR protection rules to merge this PR.

chore: Temporarily disable fail-on-error behaviour for Coveralls unit test coverable uploads in GitHub workflow

---

internal/engine/evaluator.go
internal/engine/planner/planner.go
internal/engine/ruletable/rule_table.go
internal/test/testdata/engine/case_25.yaml
internal/test/testdata/engine/case_26.yaml
internal/test/testdata/engine/case_28.yaml
internal/test/testdata/query_planner/suite/basics_scoped.yaml
internal/test/testdata/store/principal_policies/policy_02_acme.sales.yaml
internal/test/testdata/store/principal_policies/policy_02_acme.yaml
internal/test/testdata/store/resource_policies/policy_05_acme.hr.uk.brighton.yaml
internal/test/testdata/store/resource_policies/policy_05_acme.hr.uk.yaml
internal/test/testdata/store/resource_policies/policy_17.yaml

This PR encompasses two notable changes.
Principal policies with `scopePermissions: REQUIRE_PARENTAL_CONSENT` are now consistent with resource policy behaviour:
- If a rule is not matched for a given resource and action, it now falls through to parent scopes instead of instantly (implicitly) issuing a `DENY`.
- If a rule matches but the condition is not satisfied, the action is issued a `DENY`.
Unresolved resource/action pairs from a `REQUIRE_PARENTAL_CONSENT` principal policy scope can also fall through to the resource policy evaluator.
Rules defined within resource policies with `scopePermissions: REQUIRE_PARENTAL_CONSENT` now implicitly DENY actions for matching roles if a condition is defined and not satisfied. This differs from default `scopePermissions: OVERRIDE_PARENT` behaviour, …

chore!: REQUIRE_PARENTAL_CONSENT refinements for resource and principal policies

---

go.mod
internal/engine/engine.go
internal/engine/evaluator.go
internal/storage/util.go

The experimental functions in `golang.org/x/exp/maps` are now available in the standard library in Go 1.21.
Reference: https://go.dev/doc/go1.21#maps

chore: Replace `golang.org/x/exp/maps` with stdlib `maps`

---

internal/audit/file/log.go
internal/audit/file/log_test.go

Currently the file audit log backend prints arrays and objects within resource or principal attributes as JSON-encoded strings, e.g.
```json
"attr":{"claims":"[\"foo\",\"bar\"]"}
```
This PR changes the encoder to produce the expected nested JSON structures, e.g.
```json
"attr":{"claims":["foo","bar"]}
```

enhancement: Stop logging attribute values as JSON-encoded strings in decision logs

---

hack/dev/plan.hurl
internal/schema/schema.go

The schema manager should handle store reload events by purging its
cache.
Fixes #2519

fix: Purge schema cache on store reload

---

internal/parser/parser.go
internal/policy/validate.go

Return an error instead of nil when a file is empty.

chore: Handle empty policies in the parser

---

cmd/cerbos/server/server.go
internal/storage/hub/remote_source.go

Adds support for launching Cerbos with a deployment or playground from Hub.

chore: Add Hub overrides to cerbos server launch

---

internal/engine/ruletable/rule_table.go

Preserves derived role policy mappings until explicitly invalidated to ensure proper handling of dependent resource policies during policy updates. This is especially important for certain stores that send DELETE followed by ADD/UPDATE events.

fix: Maintain derived role mappings during policy updates

---

internal/compile/manager.go
internal/engine/ruletable/rule_table.go
internal/schema/schema.go
internal/storage/blob/store.go
internal/storage/db/internal/db.go
internal/storage/store.go

When an index build fails, ensure the rule table is purged to avoid operating on stale data. Adds EventDisableRuleTable event type and makes rule table rebuild from scratch on next policy event.
Also handles an issue in mutable stores where intended no-ops were generating invalid queries and breaking evaluations.

fix: Purge rule table on index build failure

---

api/genpb/cerbos/runtime/v1/hashpb_helpers.pb.go
api/genpb/cerbos/runtime/v1/runtime.pb.go
api/genpb/cerbos/runtime/v1/runtime_vtproto.pb.go
api/private/cerbos/runtime/v1/runtime.proto
internal/engine/engine.go
internal/engine/evaluator.go
internal/engine/planner/planner.go
internal/engine/ruletable/rule_table.go
internal/engine/ruletable/rule_table_test.go
internal/namer/namer.go

Extend rule table implementation to handle principal policies by adding a new policy type, separate scope maps for resource and principal policies, and methods to load and evaluate principal policies alongside resource policies.
There's decent scope for further streamlining, but I don't want to make this PR more difficult to parse than it already is. Ongoing refactors can be done in future PRs. Re-introducing tracing is one of these to-dos, for example.

feat: Add principal policy support to rule table

---

.github/workflows/pr-test.yaml

`free-disk-space` takes up the majority of the `upload-test-times` job's 5 minute timeout. We only need it because our Go cache can get very big. Overall, the time to free disk space and restore the cache ~probably~ definitely exceeds the time it would take to run `just test-times` without caching, so this PR removes the cache usage from the job (reducing the time it takes from at least 4 minutes to about 40 seconds).

chore(ci): Don't bother caching dependencies for `upload-test-times` job

---

internal/engine/engine_test.go
internal/engine/planner/ast.go
internal/engine/planner/matchers/struct_matcher.go
internal/engine/planner/planner.go
internal/engine/planner/planner_test.go
internal/engine/planner/struct_matcher.go
internal/engine/planner/struct_matcher_test.go
internal/test/testdata/query_planner/policies/resource_policies/report_with_map.yaml
internal/test/testdata/query_planner/suite/harry.yaml
internal/test/testdata/query_planner/suite/macro_user.yaml
internal/test/testdata/query_planner/suite/report_with_map.yaml

In case a collection is a known value, then `collection.exists(t, <bodyExpr>) can be simplified as a logical OR of the body expr evaluated for each value of `t` in the collection. The collection can be either a map or a list. Both single- and two-var operations are supported.

enhancement: Simplify plan with exists operation

---

deploy/charts/cerbos/values-cerbos-hub.yaml
internal/server/server_test.go
internal/storage/hub/conf.go
internal/storage/hub/conf_test.go
internal/storage/hub/local_source.go
internal/storage/hub/remote_source.go
internal/storage/hub/remote_source_test.go

If an existing configuration parameter states `bundleVersion` field, there will be an error starting up Cerbos with this change:
```json
{
"log.level": "error",
"log.logger": "cerbos.server",
"message": "Failed to start server",
"error": "failed to create store: failed to read hub configuration: yaml: unmarshal errors:\n  line 1: field bundleVersion not found in type hub.Conf"
}
```

enhancement!: Remove bundle version configuration parameter

---

go.mod
go.sum

Replaces the renamed jdxcode/netrc dependency with its new name.
Fixes #2588

chore(deps): Update cerbos-sdk-go to v0.3.2

---

docs/modules/configuration/partials/db_sync.adoc

Backports the commit [f5d113ea7a5add5b93b8fed5afc52a8c0a115baf](https://github.com/cerbos/cerbos/commit/f5d113ea7a5add5b93b8fed5afc52a8c0a115baf) to `v0.44`.

backport(docs): Fix mistake related to compile.cacheSize configuration parameter (#2598)

---

cmd/cerbos/server/server.go

fix: Don't set bundleVersion when auto-configuring hub

---

cmd/cerbosctl/hub/store/list_files.go
cmd/cerbosctl/hub/store/testdata/testscripts/store_ops.txtar
go.mod
go.sum

chore: Rename cerbosctl hub `like` filter to `contains`

---

internal/engine/planner/planner.go
internal/test/testdata/query_planner/policies/derived_roles/globex_roles.yaml
internal/test/testdata/query_planner/policies/resource_policies/stapler.yaml
internal/test/testdata/query_planner/policies/role_policies/globex_superapprover.yaml
internal/test/testdata/query_planner/suite/globex.yaml

The query planner was incorrectly handling cases where a role's DENY node was a union of constant boolean values (e.g. `OR(const true, const false)`). The existing logic only recognized singular constant true DENY nodes using `isNodeConstBool(roleDenyNode); ok && b`, but failed to identify that `OR(true, false)` is logically equivalent to `true`.
This caused inconsistent role merging/resolution as role nodes weren't being correctly normalised (`roleAllowNode = mkFalseNode`, `roleDenyNode = nil`) which then meant we had unwanted residual nodes at the point of merging those from independent roles.

fix: Handle const false DENY nodes in role-level query planning

---

go.mod
go.sum
internal/util/app.go

This can help reduce the noise in audit logs because the ID is "sticky".
Otherwise, the same PDP could get different IDs on each restart even
though it's still running on the same hardware. These IDs are still
perfectly opaque and don't reveal anything other than the fact that the
PDP is running on the same anonymous machine every time it's restarted.

enhancement: Stickier PDP IDs

---

internal/ruletable/manager.go
internal/ruletable/ruletable.go
internal/ruletable/ruletable_test.go
internal/storage/blob/store.go
internal/storage/db/internal/db.go
internal/storage/db/internal/tests.go
internal/storage/git/store_test.go
internal/storage/index/index.go
internal/storage/subscriptionmgr.go

We now leverage the store specific `GetDependents` functionality, returned in the body of the `Event` for both `AddOrUpdate` and `Delete` events. These Dependents are then reloaded in the rule table.
Added a number of test cases to prevent further regressions.

fix: Properly handle dependents on policy set updates

---

internal/util/app.go
internal/util/app_common.go
internal/util/app_stub.go

This slipped through in the rebase. It'll probably be prudent to add a CI check to ensure we don't break JS builds.

chore: Exclude machineid lib from JS builds

---

.goreleaser.yml

Remove unused "goarm" option. ARM64 doesn't support it, only ARM does.

chore(ci): Clean up .goreleaser.yml

---

e2e/blob/blob_test.go
e2e/overlay/overlay_test.go

The overlay cerbos instance and cerbos admin instance for the overlay e2e tests were running in seperate pods (talking to the same postgres instance). Storage events propogate in process, so the cerbos instance used for Check requests did not see the updated policy state. This coincidentally worked before because policies were loaded lazily. In the new pre-compiled rule table world, this is not the case. Adding a refresh after the AdminSuite run ensures policy updates were reflected in the other cerbos process.
Also increased a `sleep` in the blob e2e test to give more time for events to propogate to the rule table correctly.

fix: Fix e2e overlay test

---

e2e/blob/blob_test.go
e2e/blob/helmfile.yaml.gotmpl
internal/compile/manager.go
internal/ruletable/manager.go
internal/server/server.go
internal/server/server_test.go
internal/server/tests.go
internal/storage/blob/store.go
internal/storage/db/internal/db.go
internal/storage/db/internal/tests.go
internal/test/e2e/ctx.go
internal/test/e2e/tests.go
pkg/cerbos/serve_test.go

* Storage (blob/db): emit one deduped dependents-only event per batch;
drop per-policy dependents (there was some duplicated effort here).
* Compile manager: stop enriching all Add/Update and Delete events with
dependents as we now rely on the storage layers to handle this (there
was also some duplicated effort here).
* Rule table manager: removed the index-unhealthy gate flag. It's no
longer necessary since the compile-and-swop mechanism only mutates
rule table state on successful compilation. Processing dependents
atomically also relies on all to be available and valid in order for
mutations to occur (so links are kept consistent). Without this gate,
we bypass a large number of wasteful full reloads.
* E2E tests: I still needed to add a sleep in between the AdminSuite and
CheckSuite in …

fix: Batch dependents and deflake CI suites

---

e2e/blob/blob_test.go

I optimistically reduced it to 2 seconds (for which it sometimes successfully passes tests). However, we're still seeing flakes, so I'm tuning it back up to 5 seconds.

fix: Increase blob e2e sleep period

---

go.mod
go.sum
internal/ruletable/ruletable_test.go

Replace assertions inside require.EventuallyWithT closures to use CollectT (c) instead of *testing.T (t) so failures are correctly collected across retries and avoid flakiness and unpredictable race conditions.

fix: Use CollectT in EventuallyWithT

---

e2e/blob/blob_test.go

Passes https://github.com/cerbos/cerbos/actions/runs/17739044092/job/50408127117
Still not deterministic, but a better situation than we were in.

chore: Poll for policy existence in blob e2e tests

---

docs/modules/configuration/pages/storage.adoc

Backports the commit [f5a7d1fdbbc3eb442bfca92ec375476f7695f184](https://github.com/cerbos/cerbos/commit/f5a7d1fdbbc3eb442bfca92ec375476f7695f184) to `v0.46`.

docs(backport): Remove disableSSL and add protocol to the endpoint query param (#2715)

---

e2e/blob/helmfile.yaml.gotmpl
e2e/git/helmfile.yaml.gotmpl
e2e/lenientscopes/helmfile.yaml.gotmpl
e2e/mysql/helmfile.yaml.gotmpl
e2e/overlay/helmfile.yaml.gotmpl
e2e/postgres/helmfile.yaml.gotmpl

They have moved all images to `bitnamilegacy` repository. This is a
temporary fix until we can address #2648.

chore(ci): Use legacy Bitnami registry

---

.github/workflows/e2e.yaml
e2e/blob/blob_test.go
e2e/blob/helmfile.yaml.gotmpl

The minio chart uses several images that don't exist in the bitnami repo anymore.
Also increases the blob store sleep to 30 seconds.

chore(ci): Move all Minio images to bitnamilegacy 
